// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentificationClientInterface creates a new instance of IdentificationClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentificationClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentificationClientInterface {
	mock := &IdentificationClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentificationClientInterface is an autogenerated mock type for the IdentificationClientInterface type
type IdentificationClientInterface struct {
	mock.Mock
}

type IdentificationClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentificationClientInterface) EXPECT() *IdentificationClientInterface_Expecter {
	return &IdentificationClientInterface_Expecter{mock: &_m.Mock}
}

// RequestValues provides a mock function for the type IdentificationClientInterface
func (_mock *IdentificationClientInterface) RequestValues() (*model.MsgCounterType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestValues")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.MsgCounterType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.MsgCounterType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentificationClientInterface_RequestValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestValues'
type IdentificationClientInterface_RequestValues_Call struct {
	*mock.Call
}

// RequestValues is a helper method to define mock.On call
func (_e *IdentificationClientInterface_Expecter) RequestValues() *IdentificationClientInterface_RequestValues_Call {
	return &IdentificationClientInterface_RequestValues_Call{Call: _e.mock.On("RequestValues")}
}

func (_c *IdentificationClientInterface_RequestValues_Call) Run(run func()) *IdentificationClientInterface_RequestValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IdentificationClientInterface_RequestValues_Call) Return(msgCounterType *model.MsgCounterType, err error) *IdentificationClientInterface_RequestValues_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *IdentificationClientInterface_RequestValues_Call) RunAndReturn(run func() (*model.MsgCounterType, error)) *IdentificationClientInterface_RequestValues_Call {
	_c.Call.Return(run)
	return _c
}
