// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentificationCommonInterface creates a new instance of IdentificationCommonInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentificationCommonInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentificationCommonInterface {
	mock := &IdentificationCommonInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentificationCommonInterface is an autogenerated mock type for the IdentificationCommonInterface type
type IdentificationCommonInterface struct {
	mock.Mock
}

type IdentificationCommonInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentificationCommonInterface) EXPECT() *IdentificationCommonInterface_Expecter {
	return &IdentificationCommonInterface_Expecter{mock: &_m.Mock}
}

// CheckEventPayloadDataForFilter provides a mock function for the type IdentificationCommonInterface
func (_mock *IdentificationCommonInterface) CheckEventPayloadDataForFilter(payloadData any) bool {
	ret := _mock.Called(payloadData)

	if len(ret) == 0 {
		panic("no return value specified for CheckEventPayloadDataForFilter")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(any) bool); ok {
		r0 = returnFunc(payloadData)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEventPayloadDataForFilter'
type IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call struct {
	*mock.Call
}

// CheckEventPayloadDataForFilter is a helper method to define mock.On call
//   - payloadData any
func (_e *IdentificationCommonInterface_Expecter) CheckEventPayloadDataForFilter(payloadData interface{}) *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call {
	return &IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call{Call: _e.mock.On("CheckEventPayloadDataForFilter", payloadData)}
}

func (_c *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call) Run(run func(payloadData any)) *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call) Return(b bool) *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call) RunAndReturn(run func(payloadData any) bool) *IdentificationCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataForFilter provides a mock function for the type IdentificationCommonInterface
func (_mock *IdentificationCommonInterface) GetDataForFilter(filter model.IdentificationDataType) ([]model.IdentificationDataType, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDataForFilter")
	}

	var r0 []model.IdentificationDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.IdentificationDataType) ([]model.IdentificationDataType, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(model.IdentificationDataType) []model.IdentificationDataType); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IdentificationDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.IdentificationDataType) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentificationCommonInterface_GetDataForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataForFilter'
type IdentificationCommonInterface_GetDataForFilter_Call struct {
	*mock.Call
}

// GetDataForFilter is a helper method to define mock.On call
//   - filter model.IdentificationDataType
func (_e *IdentificationCommonInterface_Expecter) GetDataForFilter(filter interface{}) *IdentificationCommonInterface_GetDataForFilter_Call {
	return &IdentificationCommonInterface_GetDataForFilter_Call{Call: _e.mock.On("GetDataForFilter", filter)}
}

func (_c *IdentificationCommonInterface_GetDataForFilter_Call) Run(run func(filter model.IdentificationDataType)) *IdentificationCommonInterface_GetDataForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.IdentificationDataType
		if args[0] != nil {
			arg0 = args[0].(model.IdentificationDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentificationCommonInterface_GetDataForFilter_Call) Return(identificationDataTypes []model.IdentificationDataType, err error) *IdentificationCommonInterface_GetDataForFilter_Call {
	_c.Call.Return(identificationDataTypes, err)
	return _c
}

func (_c *IdentificationCommonInterface_GetDataForFilter_Call) RunAndReturn(run func(filter model.IdentificationDataType) ([]model.IdentificationDataType, error)) *IdentificationCommonInterface_GetDataForFilter_Call {
	_c.Call.Return(run)
	return _c
}
