// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIncentiveTableServerInterface creates a new instance of IncentiveTableServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncentiveTableServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncentiveTableServerInterface {
	mock := &IncentiveTableServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IncentiveTableServerInterface is an autogenerated mock type for the IncentiveTableServerInterface type
type IncentiveTableServerInterface struct {
	mock.Mock
}

type IncentiveTableServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *IncentiveTableServerInterface) EXPECT() *IncentiveTableServerInterface_Expecter {
	return &IncentiveTableServerInterface_Expecter{mock: &_m.Mock}
}
