// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/eebus-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewLoadControlServerInterface creates a new instance of LoadControlServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoadControlServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoadControlServerInterface {
	mock := &LoadControlServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoadControlServerInterface is an autogenerated mock type for the LoadControlServerInterface type
type LoadControlServerInterface struct {
	mock.Mock
}

type LoadControlServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LoadControlServerInterface) EXPECT() *LoadControlServerInterface_Expecter {
	return &LoadControlServerInterface_Expecter{mock: &_m.Mock}
}

// AddLimitDescription provides a mock function for the type LoadControlServerInterface
func (_mock *LoadControlServerInterface) AddLimitDescription(description model.LoadControlLimitDescriptionDataType) *model.LoadControlLimitIdType {
	ret := _mock.Called(description)

	if len(ret) == 0 {
		panic("no return value specified for AddLimitDescription")
	}

	var r0 *model.LoadControlLimitIdType
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitDescriptionDataType) *model.LoadControlLimitIdType); ok {
		r0 = returnFunc(description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoadControlLimitIdType)
		}
	}
	return r0
}

// LoadControlServerInterface_AddLimitDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLimitDescription'
type LoadControlServerInterface_AddLimitDescription_Call struct {
	*mock.Call
}

// AddLimitDescription is a helper method to define mock.On call
//   - description model.LoadControlLimitDescriptionDataType
func (_e *LoadControlServerInterface_Expecter) AddLimitDescription(description interface{}) *LoadControlServerInterface_AddLimitDescription_Call {
	return &LoadControlServerInterface_AddLimitDescription_Call{Call: _e.mock.On("AddLimitDescription", description)}
}

func (_c *LoadControlServerInterface_AddLimitDescription_Call) Run(run func(description model.LoadControlLimitDescriptionDataType)) *LoadControlServerInterface_AddLimitDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.LoadControlLimitDescriptionDataType
		if args[0] != nil {
			arg0 = args[0].(model.LoadControlLimitDescriptionDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlServerInterface_AddLimitDescription_Call) Return(loadControlLimitIdType *model.LoadControlLimitIdType) *LoadControlServerInterface_AddLimitDescription_Call {
	_c.Call.Return(loadControlLimitIdType)
	return _c
}

func (_c *LoadControlServerInterface_AddLimitDescription_Call) RunAndReturn(run func(description model.LoadControlLimitDescriptionDataType) *model.LoadControlLimitIdType) *LoadControlServerInterface_AddLimitDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLimitDataForFilter provides a mock function for the type LoadControlServerInterface
func (_mock *LoadControlServerInterface) UpdateLimitDataForFilter(data []api.LoadControlLimitDataForFilter, deleteSelector *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType) error {
	ret := _mock.Called(data, deleteSelector, deleteElements)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLimitDataForFilter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]api.LoadControlLimitDataForFilter, *model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) error); ok {
		r0 = returnFunc(data, deleteSelector, deleteElements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoadControlServerInterface_UpdateLimitDataForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLimitDataForFilter'
type LoadControlServerInterface_UpdateLimitDataForFilter_Call struct {
	*mock.Call
}

// UpdateLimitDataForFilter is a helper method to define mock.On call
//   - data []api.LoadControlLimitDataForFilter
//   - deleteSelector *model.LoadControlLimitListDataSelectorsType
//   - deleteElements *model.LoadControlLimitDataElementsType
func (_e *LoadControlServerInterface_Expecter) UpdateLimitDataForFilter(data interface{}, deleteSelector interface{}, deleteElements interface{}) *LoadControlServerInterface_UpdateLimitDataForFilter_Call {
	return &LoadControlServerInterface_UpdateLimitDataForFilter_Call{Call: _e.mock.On("UpdateLimitDataForFilter", data, deleteSelector, deleteElements)}
}

func (_c *LoadControlServerInterface_UpdateLimitDataForFilter_Call) Run(run func(data []api.LoadControlLimitDataForFilter, deleteSelector *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType)) *LoadControlServerInterface_UpdateLimitDataForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.LoadControlLimitDataForFilter
		if args[0] != nil {
			arg0 = args[0].([]api.LoadControlLimitDataForFilter)
		}
		var arg1 *model.LoadControlLimitListDataSelectorsType
		if args[1] != nil {
			arg1 = args[1].(*model.LoadControlLimitListDataSelectorsType)
		}
		var arg2 *model.LoadControlLimitDataElementsType
		if args[2] != nil {
			arg2 = args[2].(*model.LoadControlLimitDataElementsType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoadControlServerInterface_UpdateLimitDataForFilter_Call) Return(err error) *LoadControlServerInterface_UpdateLimitDataForFilter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoadControlServerInterface_UpdateLimitDataForFilter_Call) RunAndReturn(run func(data []api.LoadControlLimitDataForFilter, deleteSelector *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType) error) *LoadControlServerInterface_UpdateLimitDataForFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLimitDataForIds provides a mock function for the type LoadControlServerInterface
func (_mock *LoadControlServerInterface) UpdateLimitDataForIds(data []api.LoadControlLimitDataForID) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLimitDataForIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]api.LoadControlLimitDataForID) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoadControlServerInterface_UpdateLimitDataForIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLimitDataForIds'
type LoadControlServerInterface_UpdateLimitDataForIds_Call struct {
	*mock.Call
}

// UpdateLimitDataForIds is a helper method to define mock.On call
//   - data []api.LoadControlLimitDataForID
func (_e *LoadControlServerInterface_Expecter) UpdateLimitDataForIds(data interface{}) *LoadControlServerInterface_UpdateLimitDataForIds_Call {
	return &LoadControlServerInterface_UpdateLimitDataForIds_Call{Call: _e.mock.On("UpdateLimitDataForIds", data)}
}

func (_c *LoadControlServerInterface_UpdateLimitDataForIds_Call) Run(run func(data []api.LoadControlLimitDataForID)) *LoadControlServerInterface_UpdateLimitDataForIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.LoadControlLimitDataForID
		if args[0] != nil {
			arg0 = args[0].([]api.LoadControlLimitDataForID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlServerInterface_UpdateLimitDataForIds_Call) Return(err error) *LoadControlServerInterface_UpdateLimitDataForIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoadControlServerInterface_UpdateLimitDataForIds_Call) RunAndReturn(run func(data []api.LoadControlLimitDataForID) error) *LoadControlServerInterface_UpdateLimitDataForIds_Call {
	_c.Call.Return(run)
	return _c
}
