// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewLoadControlCommonInterface creates a new instance of LoadControlCommonInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoadControlCommonInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoadControlCommonInterface {
	mock := &LoadControlCommonInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoadControlCommonInterface is an autogenerated mock type for the LoadControlCommonInterface type
type LoadControlCommonInterface struct {
	mock.Mock
}

type LoadControlCommonInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LoadControlCommonInterface) EXPECT() *LoadControlCommonInterface_Expecter {
	return &LoadControlCommonInterface_Expecter{mock: &_m.Mock}
}

// CheckEventPayloadDataForFilter provides a mock function for the type LoadControlCommonInterface
func (_mock *LoadControlCommonInterface) CheckEventPayloadDataForFilter(payloadData any, filter any) bool {
	ret := _mock.Called(payloadData, filter)

	if len(ret) == 0 {
		panic("no return value specified for CheckEventPayloadDataForFilter")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(any, any) bool); ok {
		r0 = returnFunc(payloadData, filter)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEventPayloadDataForFilter'
type LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call struct {
	*mock.Call
}

// CheckEventPayloadDataForFilter is a helper method to define mock.On call
//   - payloadData any
//   - filter any
func (_e *LoadControlCommonInterface_Expecter) CheckEventPayloadDataForFilter(payloadData interface{}, filter interface{}) *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call {
	return &LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call{Call: _e.mock.On("CheckEventPayloadDataForFilter", payloadData, filter)}
}

func (_c *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call) Run(run func(payloadData any, filter any)) *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call) Return(b bool) *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call) RunAndReturn(run func(payloadData any, filter any) bool) *LoadControlCommonInterface_CheckEventPayloadDataForFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimitDataForFilter provides a mock function for the type LoadControlCommonInterface
func (_mock *LoadControlCommonInterface) GetLimitDataForFilter(filter model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDataType, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitDataForFilter")
	}

	var r0 []model.LoadControlLimitDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDataType, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitDescriptionDataType) []model.LoadControlLimitDataType); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LoadControlLimitDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.LoadControlLimitDescriptionDataType) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlCommonInterface_GetLimitDataForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitDataForFilter'
type LoadControlCommonInterface_GetLimitDataForFilter_Call struct {
	*mock.Call
}

// GetLimitDataForFilter is a helper method to define mock.On call
//   - filter model.LoadControlLimitDescriptionDataType
func (_e *LoadControlCommonInterface_Expecter) GetLimitDataForFilter(filter interface{}) *LoadControlCommonInterface_GetLimitDataForFilter_Call {
	return &LoadControlCommonInterface_GetLimitDataForFilter_Call{Call: _e.mock.On("GetLimitDataForFilter", filter)}
}

func (_c *LoadControlCommonInterface_GetLimitDataForFilter_Call) Run(run func(filter model.LoadControlLimitDescriptionDataType)) *LoadControlCommonInterface_GetLimitDataForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.LoadControlLimitDescriptionDataType
		if args[0] != nil {
			arg0 = args[0].(model.LoadControlLimitDescriptionDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDataForFilter_Call) Return(loadControlLimitDataTypes []model.LoadControlLimitDataType, err error) *LoadControlCommonInterface_GetLimitDataForFilter_Call {
	_c.Call.Return(loadControlLimitDataTypes, err)
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDataForFilter_Call) RunAndReturn(run func(filter model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDataType, error)) *LoadControlCommonInterface_GetLimitDataForFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimitDataForId provides a mock function for the type LoadControlCommonInterface
func (_mock *LoadControlCommonInterface) GetLimitDataForId(limitId model.LoadControlLimitIdType) (*model.LoadControlLimitDataType, error) {
	ret := _mock.Called(limitId)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitDataForId")
	}

	var r0 *model.LoadControlLimitDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitIdType) (*model.LoadControlLimitDataType, error)); ok {
		return returnFunc(limitId)
	}
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitIdType) *model.LoadControlLimitDataType); ok {
		r0 = returnFunc(limitId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoadControlLimitDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.LoadControlLimitIdType) error); ok {
		r1 = returnFunc(limitId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlCommonInterface_GetLimitDataForId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitDataForId'
type LoadControlCommonInterface_GetLimitDataForId_Call struct {
	*mock.Call
}

// GetLimitDataForId is a helper method to define mock.On call
//   - limitId model.LoadControlLimitIdType
func (_e *LoadControlCommonInterface_Expecter) GetLimitDataForId(limitId interface{}) *LoadControlCommonInterface_GetLimitDataForId_Call {
	return &LoadControlCommonInterface_GetLimitDataForId_Call{Call: _e.mock.On("GetLimitDataForId", limitId)}
}

func (_c *LoadControlCommonInterface_GetLimitDataForId_Call) Run(run func(limitId model.LoadControlLimitIdType)) *LoadControlCommonInterface_GetLimitDataForId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.LoadControlLimitIdType
		if args[0] != nil {
			arg0 = args[0].(model.LoadControlLimitIdType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDataForId_Call) Return(loadControlLimitDataType *model.LoadControlLimitDataType, err error) *LoadControlCommonInterface_GetLimitDataForId_Call {
	_c.Call.Return(loadControlLimitDataType, err)
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDataForId_Call) RunAndReturn(run func(limitId model.LoadControlLimitIdType) (*model.LoadControlLimitDataType, error)) *LoadControlCommonInterface_GetLimitDataForId_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimitDescriptionForId provides a mock function for the type LoadControlCommonInterface
func (_mock *LoadControlCommonInterface) GetLimitDescriptionForId(limitId model.LoadControlLimitIdType) (*model.LoadControlLimitDescriptionDataType, error) {
	ret := _mock.Called(limitId)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitDescriptionForId")
	}

	var r0 *model.LoadControlLimitDescriptionDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitIdType) (*model.LoadControlLimitDescriptionDataType, error)); ok {
		return returnFunc(limitId)
	}
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitIdType) *model.LoadControlLimitDescriptionDataType); ok {
		r0 = returnFunc(limitId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoadControlLimitDescriptionDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.LoadControlLimitIdType) error); ok {
		r1 = returnFunc(limitId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlCommonInterface_GetLimitDescriptionForId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitDescriptionForId'
type LoadControlCommonInterface_GetLimitDescriptionForId_Call struct {
	*mock.Call
}

// GetLimitDescriptionForId is a helper method to define mock.On call
//   - limitId model.LoadControlLimitIdType
func (_e *LoadControlCommonInterface_Expecter) GetLimitDescriptionForId(limitId interface{}) *LoadControlCommonInterface_GetLimitDescriptionForId_Call {
	return &LoadControlCommonInterface_GetLimitDescriptionForId_Call{Call: _e.mock.On("GetLimitDescriptionForId", limitId)}
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionForId_Call) Run(run func(limitId model.LoadControlLimitIdType)) *LoadControlCommonInterface_GetLimitDescriptionForId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.LoadControlLimitIdType
		if args[0] != nil {
			arg0 = args[0].(model.LoadControlLimitIdType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionForId_Call) Return(loadControlLimitDescriptionDataType *model.LoadControlLimitDescriptionDataType, err error) *LoadControlCommonInterface_GetLimitDescriptionForId_Call {
	_c.Call.Return(loadControlLimitDescriptionDataType, err)
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionForId_Call) RunAndReturn(run func(limitId model.LoadControlLimitIdType) (*model.LoadControlLimitDescriptionDataType, error)) *LoadControlCommonInterface_GetLimitDescriptionForId_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimitDescriptionsForFilter provides a mock function for the type LoadControlCommonInterface
func (_mock *LoadControlCommonInterface) GetLimitDescriptionsForFilter(filter model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDescriptionDataType, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitDescriptionsForFilter")
	}

	var r0 []model.LoadControlLimitDescriptionDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDescriptionDataType, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(model.LoadControlLimitDescriptionDataType) []model.LoadControlLimitDescriptionDataType); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LoadControlLimitDescriptionDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.LoadControlLimitDescriptionDataType) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitDescriptionsForFilter'
type LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call struct {
	*mock.Call
}

// GetLimitDescriptionsForFilter is a helper method to define mock.On call
//   - filter model.LoadControlLimitDescriptionDataType
func (_e *LoadControlCommonInterface_Expecter) GetLimitDescriptionsForFilter(filter interface{}) *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call {
	return &LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call{Call: _e.mock.On("GetLimitDescriptionsForFilter", filter)}
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call) Run(run func(filter model.LoadControlLimitDescriptionDataType)) *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.LoadControlLimitDescriptionDataType
		if args[0] != nil {
			arg0 = args[0].(model.LoadControlLimitDescriptionDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call) Return(loadControlLimitDescriptionDataTypes []model.LoadControlLimitDescriptionDataType, err error) *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call {
	_c.Call.Return(loadControlLimitDescriptionDataTypes, err)
	return _c
}

func (_c *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call) RunAndReturn(run func(filter model.LoadControlLimitDescriptionDataType) ([]model.LoadControlLimitDescriptionDataType, error)) *LoadControlCommonInterface_GetLimitDescriptionsForFilter_Call {
	_c.Call.Return(run)
	return _c
}
