// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewLoadControlClientInterface creates a new instance of LoadControlClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoadControlClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoadControlClientInterface {
	mock := &LoadControlClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoadControlClientInterface is an autogenerated mock type for the LoadControlClientInterface type
type LoadControlClientInterface struct {
	mock.Mock
}

type LoadControlClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LoadControlClientInterface) EXPECT() *LoadControlClientInterface_Expecter {
	return &LoadControlClientInterface_Expecter{mock: &_m.Mock}
}

// RequestLimitConstraints provides a mock function for the type LoadControlClientInterface
func (_mock *LoadControlClientInterface) RequestLimitConstraints(selector *model.LoadControlLimitConstraintsListDataSelectorsType, elements *model.LoadControlLimitConstraintsDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestLimitConstraints")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitConstraintsListDataSelectorsType, *model.LoadControlLimitConstraintsDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitConstraintsListDataSelectorsType, *model.LoadControlLimitConstraintsDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.LoadControlLimitConstraintsListDataSelectorsType, *model.LoadControlLimitConstraintsDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlClientInterface_RequestLimitConstraints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestLimitConstraints'
type LoadControlClientInterface_RequestLimitConstraints_Call struct {
	*mock.Call
}

// RequestLimitConstraints is a helper method to define mock.On call
//   - selector *model.LoadControlLimitConstraintsListDataSelectorsType
//   - elements *model.LoadControlLimitConstraintsDataElementsType
func (_e *LoadControlClientInterface_Expecter) RequestLimitConstraints(selector interface{}, elements interface{}) *LoadControlClientInterface_RequestLimitConstraints_Call {
	return &LoadControlClientInterface_RequestLimitConstraints_Call{Call: _e.mock.On("RequestLimitConstraints", selector, elements)}
}

func (_c *LoadControlClientInterface_RequestLimitConstraints_Call) Run(run func(selector *model.LoadControlLimitConstraintsListDataSelectorsType, elements *model.LoadControlLimitConstraintsDataElementsType)) *LoadControlClientInterface_RequestLimitConstraints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.LoadControlLimitConstraintsListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.LoadControlLimitConstraintsListDataSelectorsType)
		}
		var arg1 *model.LoadControlLimitConstraintsDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.LoadControlLimitConstraintsDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitConstraints_Call) Return(msgCounterType *model.MsgCounterType, err error) *LoadControlClientInterface_RequestLimitConstraints_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitConstraints_Call) RunAndReturn(run func(selector *model.LoadControlLimitConstraintsListDataSelectorsType, elements *model.LoadControlLimitConstraintsDataElementsType) (*model.MsgCounterType, error)) *LoadControlClientInterface_RequestLimitConstraints_Call {
	_c.Call.Return(run)
	return _c
}

// RequestLimitData provides a mock function for the type LoadControlClientInterface
func (_mock *LoadControlClientInterface) RequestLimitData(selector *model.LoadControlLimitListDataSelectorsType, elements *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestLimitData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlClientInterface_RequestLimitData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestLimitData'
type LoadControlClientInterface_RequestLimitData_Call struct {
	*mock.Call
}

// RequestLimitData is a helper method to define mock.On call
//   - selector *model.LoadControlLimitListDataSelectorsType
//   - elements *model.LoadControlLimitDataElementsType
func (_e *LoadControlClientInterface_Expecter) RequestLimitData(selector interface{}, elements interface{}) *LoadControlClientInterface_RequestLimitData_Call {
	return &LoadControlClientInterface_RequestLimitData_Call{Call: _e.mock.On("RequestLimitData", selector, elements)}
}

func (_c *LoadControlClientInterface_RequestLimitData_Call) Run(run func(selector *model.LoadControlLimitListDataSelectorsType, elements *model.LoadControlLimitDataElementsType)) *LoadControlClientInterface_RequestLimitData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.LoadControlLimitListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.LoadControlLimitListDataSelectorsType)
		}
		var arg1 *model.LoadControlLimitDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.LoadControlLimitDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitData_Call) Return(msgCounterType *model.MsgCounterType, err error) *LoadControlClientInterface_RequestLimitData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitData_Call) RunAndReturn(run func(selector *model.LoadControlLimitListDataSelectorsType, elements *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error)) *LoadControlClientInterface_RequestLimitData_Call {
	_c.Call.Return(run)
	return _c
}

// RequestLimitDescriptions provides a mock function for the type LoadControlClientInterface
func (_mock *LoadControlClientInterface) RequestLimitDescriptions(selector *model.LoadControlLimitDescriptionListDataSelectorsType, elements *model.LoadControlLimitDescriptionDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestLimitDescriptions")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitDescriptionListDataSelectorsType, *model.LoadControlLimitDescriptionDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.LoadControlLimitDescriptionListDataSelectorsType, *model.LoadControlLimitDescriptionDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.LoadControlLimitDescriptionListDataSelectorsType, *model.LoadControlLimitDescriptionDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlClientInterface_RequestLimitDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestLimitDescriptions'
type LoadControlClientInterface_RequestLimitDescriptions_Call struct {
	*mock.Call
}

// RequestLimitDescriptions is a helper method to define mock.On call
//   - selector *model.LoadControlLimitDescriptionListDataSelectorsType
//   - elements *model.LoadControlLimitDescriptionDataElementsType
func (_e *LoadControlClientInterface_Expecter) RequestLimitDescriptions(selector interface{}, elements interface{}) *LoadControlClientInterface_RequestLimitDescriptions_Call {
	return &LoadControlClientInterface_RequestLimitDescriptions_Call{Call: _e.mock.On("RequestLimitDescriptions", selector, elements)}
}

func (_c *LoadControlClientInterface_RequestLimitDescriptions_Call) Run(run func(selector *model.LoadControlLimitDescriptionListDataSelectorsType, elements *model.LoadControlLimitDescriptionDataElementsType)) *LoadControlClientInterface_RequestLimitDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.LoadControlLimitDescriptionListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.LoadControlLimitDescriptionListDataSelectorsType)
		}
		var arg1 *model.LoadControlLimitDescriptionDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.LoadControlLimitDescriptionDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitDescriptions_Call) Return(msgCounterType *model.MsgCounterType, err error) *LoadControlClientInterface_RequestLimitDescriptions_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *LoadControlClientInterface_RequestLimitDescriptions_Call) RunAndReturn(run func(selector *model.LoadControlLimitDescriptionListDataSelectorsType, elements *model.LoadControlLimitDescriptionDataElementsType) (*model.MsgCounterType, error)) *LoadControlClientInterface_RequestLimitDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLimitData provides a mock function for the type LoadControlClientInterface
func (_mock *LoadControlClientInterface) WriteLimitData(data []model.LoadControlLimitDataType, deleteSelectors *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(data, deleteSelectors, deleteElements)

	if len(ret) == 0 {
		panic("no return value specified for WriteLimitData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]model.LoadControlLimitDataType, *model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(data, deleteSelectors, deleteElements)
	}
	if returnFunc, ok := ret.Get(0).(func([]model.LoadControlLimitDataType, *model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(data, deleteSelectors, deleteElements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]model.LoadControlLimitDataType, *model.LoadControlLimitListDataSelectorsType, *model.LoadControlLimitDataElementsType) error); ok {
		r1 = returnFunc(data, deleteSelectors, deleteElements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoadControlClientInterface_WriteLimitData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLimitData'
type LoadControlClientInterface_WriteLimitData_Call struct {
	*mock.Call
}

// WriteLimitData is a helper method to define mock.On call
//   - data []model.LoadControlLimitDataType
//   - deleteSelectors *model.LoadControlLimitListDataSelectorsType
//   - deleteElements *model.LoadControlLimitDataElementsType
func (_e *LoadControlClientInterface_Expecter) WriteLimitData(data interface{}, deleteSelectors interface{}, deleteElements interface{}) *LoadControlClientInterface_WriteLimitData_Call {
	return &LoadControlClientInterface_WriteLimitData_Call{Call: _e.mock.On("WriteLimitData", data, deleteSelectors, deleteElements)}
}

func (_c *LoadControlClientInterface_WriteLimitData_Call) Run(run func(data []model.LoadControlLimitDataType, deleteSelectors *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType)) *LoadControlClientInterface_WriteLimitData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []model.LoadControlLimitDataType
		if args[0] != nil {
			arg0 = args[0].([]model.LoadControlLimitDataType)
		}
		var arg1 *model.LoadControlLimitListDataSelectorsType
		if args[1] != nil {
			arg1 = args[1].(*model.LoadControlLimitListDataSelectorsType)
		}
		var arg2 *model.LoadControlLimitDataElementsType
		if args[2] != nil {
			arg2 = args[2].(*model.LoadControlLimitDataElementsType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoadControlClientInterface_WriteLimitData_Call) Return(msgCounterType *model.MsgCounterType, err error) *LoadControlClientInterface_WriteLimitData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *LoadControlClientInterface_WriteLimitData_Call) RunAndReturn(run func(data []model.LoadControlLimitDataType, deleteSelectors *model.LoadControlLimitListDataSelectorsType, deleteElements *model.LoadControlLimitDataElementsType) (*model.MsgCounterType, error)) *LoadControlClientInterface_WriteLimitData_Call {
	_c.Call.Return(run)
	return _c
}
