// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMeasurementClientInterface creates a new instance of MeasurementClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeasurementClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeasurementClientInterface {
	mock := &MeasurementClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MeasurementClientInterface is an autogenerated mock type for the MeasurementClientInterface type
type MeasurementClientInterface struct {
	mock.Mock
}

type MeasurementClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MeasurementClientInterface) EXPECT() *MeasurementClientInterface_Expecter {
	return &MeasurementClientInterface_Expecter{mock: &_m.Mock}
}

// RequestConstraints provides a mock function for the type MeasurementClientInterface
func (_mock *MeasurementClientInterface) RequestConstraints(selector *model.MeasurementConstraintsListDataSelectorsType, elements *model.MeasurementConstraintsDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestConstraints")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementConstraintsListDataSelectorsType, *model.MeasurementConstraintsDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementConstraintsListDataSelectorsType, *model.MeasurementConstraintsDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.MeasurementConstraintsListDataSelectorsType, *model.MeasurementConstraintsDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MeasurementClientInterface_RequestConstraints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestConstraints'
type MeasurementClientInterface_RequestConstraints_Call struct {
	*mock.Call
}

// RequestConstraints is a helper method to define mock.On call
//   - selector *model.MeasurementConstraintsListDataSelectorsType
//   - elements *model.MeasurementConstraintsDataElementsType
func (_e *MeasurementClientInterface_Expecter) RequestConstraints(selector interface{}, elements interface{}) *MeasurementClientInterface_RequestConstraints_Call {
	return &MeasurementClientInterface_RequestConstraints_Call{Call: _e.mock.On("RequestConstraints", selector, elements)}
}

func (_c *MeasurementClientInterface_RequestConstraints_Call) Run(run func(selector *model.MeasurementConstraintsListDataSelectorsType, elements *model.MeasurementConstraintsDataElementsType)) *MeasurementClientInterface_RequestConstraints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.MeasurementConstraintsListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.MeasurementConstraintsListDataSelectorsType)
		}
		var arg1 *model.MeasurementConstraintsDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.MeasurementConstraintsDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MeasurementClientInterface_RequestConstraints_Call) Return(msgCounterType *model.MsgCounterType, err error) *MeasurementClientInterface_RequestConstraints_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *MeasurementClientInterface_RequestConstraints_Call) RunAndReturn(run func(selector *model.MeasurementConstraintsListDataSelectorsType, elements *model.MeasurementConstraintsDataElementsType) (*model.MsgCounterType, error)) *MeasurementClientInterface_RequestConstraints_Call {
	_c.Call.Return(run)
	return _c
}

// RequestData provides a mock function for the type MeasurementClientInterface
func (_mock *MeasurementClientInterface) RequestData(selector *model.MeasurementListDataSelectorsType, elements *model.MeasurementDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementListDataSelectorsType, *model.MeasurementDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementListDataSelectorsType, *model.MeasurementDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.MeasurementListDataSelectorsType, *model.MeasurementDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MeasurementClientInterface_RequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestData'
type MeasurementClientInterface_RequestData_Call struct {
	*mock.Call
}

// RequestData is a helper method to define mock.On call
//   - selector *model.MeasurementListDataSelectorsType
//   - elements *model.MeasurementDataElementsType
func (_e *MeasurementClientInterface_Expecter) RequestData(selector interface{}, elements interface{}) *MeasurementClientInterface_RequestData_Call {
	return &MeasurementClientInterface_RequestData_Call{Call: _e.mock.On("RequestData", selector, elements)}
}

func (_c *MeasurementClientInterface_RequestData_Call) Run(run func(selector *model.MeasurementListDataSelectorsType, elements *model.MeasurementDataElementsType)) *MeasurementClientInterface_RequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.MeasurementListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.MeasurementListDataSelectorsType)
		}
		var arg1 *model.MeasurementDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.MeasurementDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MeasurementClientInterface_RequestData_Call) Return(msgCounterType *model.MsgCounterType, err error) *MeasurementClientInterface_RequestData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *MeasurementClientInterface_RequestData_Call) RunAndReturn(run func(selector *model.MeasurementListDataSelectorsType, elements *model.MeasurementDataElementsType) (*model.MsgCounterType, error)) *MeasurementClientInterface_RequestData_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDescriptions provides a mock function for the type MeasurementClientInterface
func (_mock *MeasurementClientInterface) RequestDescriptions(selector *model.MeasurementDescriptionListDataSelectorsType, elements *model.MeasurementDescriptionDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestDescriptions")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementDescriptionListDataSelectorsType, *model.MeasurementDescriptionDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.MeasurementDescriptionListDataSelectorsType, *model.MeasurementDescriptionDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.MeasurementDescriptionListDataSelectorsType, *model.MeasurementDescriptionDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MeasurementClientInterface_RequestDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDescriptions'
type MeasurementClientInterface_RequestDescriptions_Call struct {
	*mock.Call
}

// RequestDescriptions is a helper method to define mock.On call
//   - selector *model.MeasurementDescriptionListDataSelectorsType
//   - elements *model.MeasurementDescriptionDataElementsType
func (_e *MeasurementClientInterface_Expecter) RequestDescriptions(selector interface{}, elements interface{}) *MeasurementClientInterface_RequestDescriptions_Call {
	return &MeasurementClientInterface_RequestDescriptions_Call{Call: _e.mock.On("RequestDescriptions", selector, elements)}
}

func (_c *MeasurementClientInterface_RequestDescriptions_Call) Run(run func(selector *model.MeasurementDescriptionListDataSelectorsType, elements *model.MeasurementDescriptionDataElementsType)) *MeasurementClientInterface_RequestDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.MeasurementDescriptionListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.MeasurementDescriptionListDataSelectorsType)
		}
		var arg1 *model.MeasurementDescriptionDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.MeasurementDescriptionDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MeasurementClientInterface_RequestDescriptions_Call) Return(msgCounterType *model.MsgCounterType, err error) *MeasurementClientInterface_RequestDescriptions_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *MeasurementClientInterface_RequestDescriptions_Call) RunAndReturn(run func(selector *model.MeasurementDescriptionListDataSelectorsType, elements *model.MeasurementDescriptionDataElementsType) (*model.MsgCounterType, error)) *MeasurementClientInterface_RequestDescriptions_Call {
	_c.Call.Return(run)
	return _c
}
