// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	api0 "github.com/enbility/eebus-go/api"
	api1 "github.com/enbility/eebus-go/usecases/api"
	"github.com/enbility/spine-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMuMPCInterface creates a new instance of MuMPCInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMuMPCInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MuMPCInterface {
	mock := &MuMPCInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MuMPCInterface is an autogenerated mock type for the MuMPCInterface type
type MuMPCInterface struct {
	mock.Mock
}

type MuMPCInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MuMPCInterface) EXPECT() *MuMPCInterface_Expecter {
	return &MuMPCInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) AddFeatures() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddFeatures")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MuMPCInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type MuMPCInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) AddFeatures() *MuMPCInterface_AddFeatures_Call {
	return &MuMPCInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *MuMPCInterface_AddFeatures_Call) Run(run func()) *MuMPCInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_AddFeatures_Call) Return(err error) *MuMPCInterface_AddFeatures_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MuMPCInterface_AddFeatures_Call) RunAndReturn(run func() error) *MuMPCInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) AddUseCase() {
	_mock.Called()
	return
}

// MuMPCInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type MuMPCInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) AddUseCase() *MuMPCInterface_AddUseCase_Call {
	return &MuMPCInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *MuMPCInterface_AddUseCase_Call) Run(run func()) *MuMPCInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_AddUseCase_Call) Return() *MuMPCInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MuMPCInterface_AddUseCase_Call) RunAndReturn(run func()) *MuMPCInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// MuMPCInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type MuMPCInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *MuMPCInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *MuMPCInterface_AvailableScenariosForEntity_Call {
	return &MuMPCInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *MuMPCInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *MuMPCInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MuMPCInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *MuMPCInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *MuMPCInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *MuMPCInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentPerPhase provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) CurrentPerPhase() (map[model.ElectricalConnectionPhaseNameType]float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentPerPhase")
	}

	var r0 map[model.ElectricalConnectionPhaseNameType]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[model.ElectricalConnectionPhaseNameType]float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[model.ElectricalConnectionPhaseNameType]float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.ElectricalConnectionPhaseNameType]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_CurrentPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPerPhase'
type MuMPCInterface_CurrentPerPhase_Call struct {
	*mock.Call
}

// CurrentPerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) CurrentPerPhase() *MuMPCInterface_CurrentPerPhase_Call {
	return &MuMPCInterface_CurrentPerPhase_Call{Call: _e.mock.On("CurrentPerPhase")}
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) Run(run func()) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) Return(electricalConnectionPhaseNameTypeToFloat64 map[model.ElectricalConnectionPhaseNameType]float64, err error) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Return(electricalConnectionPhaseNameTypeToFloat64, err)
	return _c
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) RunAndReturn(run func() (map[model.ElectricalConnectionPhaseNameType]float64, error)) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyConsumed provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) EnergyConsumed() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyConsumed")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_EnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyConsumed'
type MuMPCInterface_EnergyConsumed_Call struct {
	*mock.Call
}

// EnergyConsumed is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) EnergyConsumed() *MuMPCInterface_EnergyConsumed_Call {
	return &MuMPCInterface_EnergyConsumed_Call{Call: _e.mock.On("EnergyConsumed")}
}

func (_c *MuMPCInterface_EnergyConsumed_Call) Run(run func()) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_EnergyConsumed_Call) Return(f float64, err error) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MuMPCInterface_EnergyConsumed_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyProduced provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) EnergyProduced() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyProduced")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_EnergyProduced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyProduced'
type MuMPCInterface_EnergyProduced_Call struct {
	*mock.Call
}

// EnergyProduced is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) EnergyProduced() *MuMPCInterface_EnergyProduced_Call {
	return &MuMPCInterface_EnergyProduced_Call{Call: _e.mock.On("EnergyProduced")}
}

func (_c *MuMPCInterface_EnergyProduced_Call) Run(run func()) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_EnergyProduced_Call) Return(f float64, err error) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MuMPCInterface_EnergyProduced_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Return(run)
	return _c
}

// Frequency provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) Frequency() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Frequency")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_Frequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Frequency'
type MuMPCInterface_Frequency_Call struct {
	*mock.Call
}

// Frequency is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) Frequency() *MuMPCInterface_Frequency_Call {
	return &MuMPCInterface_Frequency_Call{Call: _e.mock.On("Frequency")}
}

func (_c *MuMPCInterface_Frequency_Call) Run(run func()) *MuMPCInterface_Frequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_Frequency_Call) Return(f float64, err error) *MuMPCInterface_Frequency_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MuMPCInterface_Frequency_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_Frequency_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MuMPCInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type MuMPCInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *MuMPCInterface_Expecter) IsCompatibleEntityType(entity interface{}) *MuMPCInterface_IsCompatibleEntityType_Call {
	return &MuMPCInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *MuMPCInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *MuMPCInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MuMPCInterface_IsCompatibleEntityType_Call) Return(b bool) *MuMPCInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MuMPCInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *MuMPCInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MuMPCInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type MuMPCInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *MuMPCInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *MuMPCInterface_IsScenarioAvailableAtEntity_Call {
	return &MuMPCInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *MuMPCInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *MuMPCInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MuMPCInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *MuMPCInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MuMPCInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *MuMPCInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// Power provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) Power() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Power")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_Power_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Power'
type MuMPCInterface_Power_Call struct {
	*mock.Call
}

// Power is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) Power() *MuMPCInterface_Power_Call {
	return &MuMPCInterface_Power_Call{Call: _e.mock.On("Power")}
}

func (_c *MuMPCInterface_Power_Call) Run(run func()) *MuMPCInterface_Power_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_Power_Call) Return(f float64, err error) *MuMPCInterface_Power_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MuMPCInterface_Power_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_Power_Call {
	_c.Call.Return(run)
	return _c
}

// PowerPerPhase provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) PowerPerPhase() (map[model.ElectricalConnectionPhaseNameType]float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PowerPerPhase")
	}

	var r0 map[model.ElectricalConnectionPhaseNameType]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[model.ElectricalConnectionPhaseNameType]float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[model.ElectricalConnectionPhaseNameType]float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.ElectricalConnectionPhaseNameType]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_PowerPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerPerPhase'
type MuMPCInterface_PowerPerPhase_Call struct {
	*mock.Call
}

// PowerPerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) PowerPerPhase() *MuMPCInterface_PowerPerPhase_Call {
	return &MuMPCInterface_PowerPerPhase_Call{Call: _e.mock.On("PowerPerPhase")}
}

func (_c *MuMPCInterface_PowerPerPhase_Call) Run(run func()) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_PowerPerPhase_Call) Return(electricalConnectionPhaseNameTypeToFloat64 map[model.ElectricalConnectionPhaseNameType]float64, err error) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Return(electricalConnectionPhaseNameTypeToFloat64, err)
	return _c
}

func (_c *MuMPCInterface_PowerPerPhase_Call) RunAndReturn(run func() (map[model.ElectricalConnectionPhaseNameType]float64, error)) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) RemoteEntitiesScenarios() []api0.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api0.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api0.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.RemoteEntityScenarios)
		}
	}
	return r0
}

// MuMPCInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type MuMPCInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) RemoteEntitiesScenarios() *MuMPCInterface_RemoteEntitiesScenarios_Call {
	return &MuMPCInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *MuMPCInterface_RemoteEntitiesScenarios_Call) Run(run func()) *MuMPCInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api0.RemoteEntityScenarios) *MuMPCInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *MuMPCInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api0.RemoteEntityScenarios) *MuMPCInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// MuMPCInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type MuMPCInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) RemoveUseCase() *MuMPCInterface_RemoveUseCase_Call {
	return &MuMPCInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *MuMPCInterface_RemoveUseCase_Call) Run(run func()) *MuMPCInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_RemoveUseCase_Call) Return() *MuMPCInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MuMPCInterface_RemoveUseCase_Call) RunAndReturn(run func()) *MuMPCInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) Update(data ...api1.UpdateMeasurementData) error {
	var tmpRet mock.Arguments
	if len(data) > 0 {
		tmpRet = _mock.Called(data)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...api1.UpdateMeasurementData) error); ok {
		r0 = returnFunc(data...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MuMPCInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MuMPCInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - data ...api1.UpdateMeasurementData
func (_e *MuMPCInterface_Expecter) Update(data ...interface{}) *MuMPCInterface_Update_Call {
	return &MuMPCInterface_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{}, data...)...)}
}

func (_c *MuMPCInterface_Update_Call) Run(run func(data ...api1.UpdateMeasurementData)) *MuMPCInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api1.UpdateMeasurementData
		var variadicArgs []api1.UpdateMeasurementData
		if len(args) > 0 {
			variadicArgs = args[0].([]api1.UpdateMeasurementData)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MuMPCInterface_Update_Call) Return(err error) *MuMPCInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MuMPCInterface_Update_Call) RunAndReturn(run func(data ...api1.UpdateMeasurementData) error) *MuMPCInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseA provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataCurrentPhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseA")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseA'
type MuMPCInterface_UpdateDataCurrentPhaseA_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseA_Call{Call: _e.mock.On("UpdateDataCurrentPhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseB provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataCurrentPhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseB")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseB'
type MuMPCInterface_UpdateDataCurrentPhaseB_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseB_Call{Call: _e.mock.On("UpdateDataCurrentPhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseC provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataCurrentPhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseC")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseC'
type MuMPCInterface_UpdateDataCurrentPhaseC_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseC_Call{Call: _e.mock.On("UpdateDataCurrentPhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyConsumed provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataEnergyConsumed(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState, evaluationStart, evaluationEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyConsumed")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState, evaluationStart, evaluationEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataEnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyConsumed'
type MuMPCInterface_UpdateDataEnergyConsumed_Call struct {
	*mock.Call
}

// UpdateDataEnergyConsumed is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationStart *time.Time
//   - evaluationEnd *time.Time
func (_e *MuMPCInterface_Expecter) UpdateDataEnergyConsumed(value interface{}, timestamp interface{}, valueState interface{}, evaluationStart interface{}, evaluationEnd interface{}) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	return &MuMPCInterface_UpdateDataEnergyConsumed_Call{Call: _e.mock.On("UpdateDataEnergyConsumed", value, timestamp, valueState, evaluationStart, evaluationEnd)}
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time)) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyProduced provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataEnergyProduced(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState, evaluationStart, evaluationEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyProduced")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState, evaluationStart, evaluationEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataEnergyProduced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyProduced'
type MuMPCInterface_UpdateDataEnergyProduced_Call struct {
	*mock.Call
}

// UpdateDataEnergyProduced is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationStart *time.Time
//   - evaluationEnd *time.Time
func (_e *MuMPCInterface_Expecter) UpdateDataEnergyProduced(value interface{}, timestamp interface{}, valueState interface{}, evaluationStart interface{}, evaluationEnd interface{}) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	return &MuMPCInterface_UpdateDataEnergyProduced_Call{Call: _e.mock.On("UpdateDataEnergyProduced", value, timestamp, valueState, evaluationStart, evaluationEnd)}
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time)) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataFrequency provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataFrequency(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataFrequency")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataFrequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataFrequency'
type MuMPCInterface_UpdateDataFrequency_Call struct {
	*mock.Call
}

// UpdateDataFrequency is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataFrequency(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataFrequency_Call {
	return &MuMPCInterface_UpdateDataFrequency_Call{Call: _e.mock.On("UpdateDataFrequency", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseA provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataPowerPhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseA")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseA'
type MuMPCInterface_UpdateDataPowerPhaseA_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseA_Call{Call: _e.mock.On("UpdateDataPowerPhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseB provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataPowerPhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseB")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseB'
type MuMPCInterface_UpdateDataPowerPhaseB_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseB_Call{Call: _e.mock.On("UpdateDataPowerPhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseC provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataPowerPhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseC")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseC'
type MuMPCInterface_UpdateDataPowerPhaseC_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseC_Call{Call: _e.mock.On("UpdateDataPowerPhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerTotal provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataPowerTotal(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerTotal")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataPowerTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerTotal'
type MuMPCInterface_UpdateDataPowerTotal_Call struct {
	*mock.Call
}

// UpdateDataPowerTotal is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerTotal(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerTotal_Call {
	return &MuMPCInterface_UpdateDataPowerTotal_Call{Call: _e.mock.On("UpdateDataPowerTotal", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseA provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseA")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseA'
type MuMPCInterface_UpdateDataVoltagePhaseA_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseA_Call{Call: _e.mock.On("UpdateDataVoltagePhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseAToB provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseAToB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseAToB")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseAToB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseAToB'
type MuMPCInterface_UpdateDataVoltagePhaseAToB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseAToB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseAToB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseAToB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseAToB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseAToC provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseAToC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseAToC")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseAToC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseAToC'
type MuMPCInterface_UpdateDataVoltagePhaseAToC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseAToC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseAToC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseAToC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseAToC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseB provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseB")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseB'
type MuMPCInterface_UpdateDataVoltagePhaseB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseBToC provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseBToC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseBToC")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseBToC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseBToC'
type MuMPCInterface_UpdateDataVoltagePhaseBToC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseBToC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseBToC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseBToC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseBToC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseC provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateDataVoltagePhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseC")
	}

	var r0 api1.UpdateMeasurementData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateMeasurementData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateMeasurementData)
		}
	}
	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseC'
type MuMPCInterface_UpdateDataVoltagePhaseC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) Return(updateMeasurementData api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(updateMeasurementData)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// MuMPCInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type MuMPCInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *MuMPCInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *MuMPCInterface_UpdateUseCaseAvailability_Call {
	return &MuMPCInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *MuMPCInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *MuMPCInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MuMPCInterface_UpdateUseCaseAvailability_Call) Return() *MuMPCInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *MuMPCInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *MuMPCInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}

// VoltagePerPhase provides a mock function for the type MuMPCInterface
func (_mock *MuMPCInterface) VoltagePerPhase() (map[model.ElectricalConnectionPhaseNameType]float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VoltagePerPhase")
	}

	var r0 map[model.ElectricalConnectionPhaseNameType]float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[model.ElectricalConnectionPhaseNameType]float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[model.ElectricalConnectionPhaseNameType]float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.ElectricalConnectionPhaseNameType]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MuMPCInterface_VoltagePerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoltagePerPhase'
type MuMPCInterface_VoltagePerPhase_Call struct {
	*mock.Call
}

// VoltagePerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) VoltagePerPhase() *MuMPCInterface_VoltagePerPhase_Call {
	return &MuMPCInterface_VoltagePerPhase_Call{Call: _e.mock.On("VoltagePerPhase")}
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) Run(run func()) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) Return(electricalConnectionPhaseNameTypeToFloat64 map[model.ElectricalConnectionPhaseNameType]float64, err error) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Return(electricalConnectionPhaseNameTypeToFloat64, err)
	return _c
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) RunAndReturn(run func() (map[model.ElectricalConnectionPhaseNameType]float64, error)) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Return(run)
	return _c
}
