// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateConfigurationData creates a new instance of UpdateConfigurationData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateConfigurationData(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateConfigurationData {
	mock := &UpdateConfigurationData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateConfigurationData is an autogenerated mock type for the UpdateConfigurationData type
type UpdateConfigurationData struct {
	mock.Mock
}

type UpdateConfigurationData_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateConfigurationData) EXPECT() *UpdateConfigurationData_Expecter {
	return &UpdateConfigurationData_Expecter{mock: &_m.Mock}
}

// ConfigurationData provides a mock function for the type UpdateConfigurationData
func (_mock *UpdateConfigurationData) ConfigurationData() model.DeviceConfigurationKeyValueDataType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigurationData")
	}

	var r0 model.DeviceConfigurationKeyValueDataType
	if returnFunc, ok := ret.Get(0).(func() model.DeviceConfigurationKeyValueDataType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.DeviceConfigurationKeyValueDataType)
	}
	return r0
}

// UpdateConfigurationData_ConfigurationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigurationData'
type UpdateConfigurationData_ConfigurationData_Call struct {
	*mock.Call
}

// ConfigurationData is a helper method to define mock.On call
func (_e *UpdateConfigurationData_Expecter) ConfigurationData() *UpdateConfigurationData_ConfigurationData_Call {
	return &UpdateConfigurationData_ConfigurationData_Call{Call: _e.mock.On("ConfigurationData")}
}

func (_c *UpdateConfigurationData_ConfigurationData_Call) Run(run func()) *UpdateConfigurationData_ConfigurationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateConfigurationData_ConfigurationData_Call) Return(deviceConfigurationKeyValueDataType model.DeviceConfigurationKeyValueDataType) *UpdateConfigurationData_ConfigurationData_Call {
	_c.Call.Return(deviceConfigurationKeyValueDataType)
	return _c
}

func (_c *UpdateConfigurationData_ConfigurationData_Call) RunAndReturn(run func() model.DeviceConfigurationKeyValueDataType) *UpdateConfigurationData_ConfigurationData_Call {
	_c.Call.Return(run)
	return _c
}

// NotSupportedError provides a mock function for the type UpdateConfigurationData
func (_mock *UpdateConfigurationData) NotSupportedError() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotSupportedError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UpdateConfigurationData_NotSupportedError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotSupportedError'
type UpdateConfigurationData_NotSupportedError_Call struct {
	*mock.Call
}

// NotSupportedError is a helper method to define mock.On call
func (_e *UpdateConfigurationData_Expecter) NotSupportedError() *UpdateConfigurationData_NotSupportedError_Call {
	return &UpdateConfigurationData_NotSupportedError_Call{Call: _e.mock.On("NotSupportedError")}
}

func (_c *UpdateConfigurationData_NotSupportedError_Call) Run(run func()) *UpdateConfigurationData_NotSupportedError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateConfigurationData_NotSupportedError_Call) Return(err error) *UpdateConfigurationData_NotSupportedError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UpdateConfigurationData_NotSupportedError_Call) RunAndReturn(run func() error) *UpdateConfigurationData_NotSupportedError_Call {
	_c.Call.Return(run)
	return _c
}

// Supported provides a mock function for the type UpdateConfigurationData
func (_mock *UpdateConfigurationData) Supported() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Supported")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// UpdateConfigurationData_Supported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supported'
type UpdateConfigurationData_Supported_Call struct {
	*mock.Call
}

// Supported is a helper method to define mock.On call
func (_e *UpdateConfigurationData_Expecter) Supported() *UpdateConfigurationData_Supported_Call {
	return &UpdateConfigurationData_Supported_Call{Call: _e.mock.On("Supported")}
}

func (_c *UpdateConfigurationData_Supported_Call) Run(run func()) *UpdateConfigurationData_Supported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateConfigurationData_Supported_Call) Return(b bool) *UpdateConfigurationData_Supported_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *UpdateConfigurationData_Supported_Call) RunAndReturn(run func() bool) *UpdateConfigurationData_Supported_Call {
	_c.Call.Return(run)
	return _c
}
