// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	api0 "github.com/enbility/eebus-go/api"
	api1 "github.com/enbility/eebus-go/usecases/api"
	"github.com/enbility/spine-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewGcpMGCPInterface creates a new instance of GcpMGCPInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGcpMGCPInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GcpMGCPInterface {
	mock := &GcpMGCPInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GcpMGCPInterface is an autogenerated mock type for the GcpMGCPInterface type
type GcpMGCPInterface struct {
	mock.Mock
}

type GcpMGCPInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *GcpMGCPInterface) EXPECT() *GcpMGCPInterface_Expecter {
	return &GcpMGCPInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) AddFeatures() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddFeatures")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GcpMGCPInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type GcpMGCPInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) AddFeatures() *GcpMGCPInterface_AddFeatures_Call {
	return &GcpMGCPInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *GcpMGCPInterface_AddFeatures_Call) Run(run func()) *GcpMGCPInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_AddFeatures_Call) Return(err error) *GcpMGCPInterface_AddFeatures_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GcpMGCPInterface_AddFeatures_Call) RunAndReturn(run func() error) *GcpMGCPInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) AddUseCase() {
	_mock.Called()
	return
}

// GcpMGCPInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type GcpMGCPInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) AddUseCase() *GcpMGCPInterface_AddUseCase_Call {
	return &GcpMGCPInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *GcpMGCPInterface_AddUseCase_Call) Run(run func()) *GcpMGCPInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_AddUseCase_Call) Return() *GcpMGCPInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *GcpMGCPInterface_AddUseCase_Call) RunAndReturn(run func()) *GcpMGCPInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// GcpMGCPInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type GcpMGCPInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *GcpMGCPInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *GcpMGCPInterface_AvailableScenariosForEntity_Call {
	return &GcpMGCPInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *GcpMGCPInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *GcpMGCPInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *GcpMGCPInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *GcpMGCPInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *GcpMGCPInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentPerPhase provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) CurrentPerPhase() ([]float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentPerPhase")
	}

	var r0 []float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_CurrentPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPerPhase'
type GcpMGCPInterface_CurrentPerPhase_Call struct {
	*mock.Call
}

// CurrentPerPhase is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) CurrentPerPhase() *GcpMGCPInterface_CurrentPerPhase_Call {
	return &GcpMGCPInterface_CurrentPerPhase_Call{Call: _e.mock.On("CurrentPerPhase")}
}

func (_c *GcpMGCPInterface_CurrentPerPhase_Call) Run(run func()) *GcpMGCPInterface_CurrentPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_CurrentPerPhase_Call) Return(float64s []float64, err error) *GcpMGCPInterface_CurrentPerPhase_Call {
	_c.Call.Return(float64s, err)
	return _c
}

func (_c *GcpMGCPInterface_CurrentPerPhase_Call) RunAndReturn(run func() ([]float64, error)) *GcpMGCPInterface_CurrentPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyConsumed provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) EnergyConsumed() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyConsumed")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_EnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyConsumed'
type GcpMGCPInterface_EnergyConsumed_Call struct {
	*mock.Call
}

// EnergyConsumed is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) EnergyConsumed() *GcpMGCPInterface_EnergyConsumed_Call {
	return &GcpMGCPInterface_EnergyConsumed_Call{Call: _e.mock.On("EnergyConsumed")}
}

func (_c *GcpMGCPInterface_EnergyConsumed_Call) Run(run func()) *GcpMGCPInterface_EnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_EnergyConsumed_Call) Return(f float64, err error) *GcpMGCPInterface_EnergyConsumed_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *GcpMGCPInterface_EnergyConsumed_Call) RunAndReturn(run func() (float64, error)) *GcpMGCPInterface_EnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyFeedIn provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) EnergyFeedIn() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyFeedIn")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_EnergyFeedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyFeedIn'
type GcpMGCPInterface_EnergyFeedIn_Call struct {
	*mock.Call
}

// EnergyFeedIn is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) EnergyFeedIn() *GcpMGCPInterface_EnergyFeedIn_Call {
	return &GcpMGCPInterface_EnergyFeedIn_Call{Call: _e.mock.On("EnergyFeedIn")}
}

func (_c *GcpMGCPInterface_EnergyFeedIn_Call) Run(run func()) *GcpMGCPInterface_EnergyFeedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_EnergyFeedIn_Call) Return(f float64, err error) *GcpMGCPInterface_EnergyFeedIn_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *GcpMGCPInterface_EnergyFeedIn_Call) RunAndReturn(run func() (float64, error)) *GcpMGCPInterface_EnergyFeedIn_Call {
	_c.Call.Return(run)
	return _c
}

// Frequency provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) Frequency() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Frequency")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_Frequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Frequency'
type GcpMGCPInterface_Frequency_Call struct {
	*mock.Call
}

// Frequency is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) Frequency() *GcpMGCPInterface_Frequency_Call {
	return &GcpMGCPInterface_Frequency_Call{Call: _e.mock.On("Frequency")}
}

func (_c *GcpMGCPInterface_Frequency_Call) Run(run func()) *GcpMGCPInterface_Frequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_Frequency_Call) Return(f float64, err error) *GcpMGCPInterface_Frequency_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *GcpMGCPInterface_Frequency_Call) RunAndReturn(run func() (float64, error)) *GcpMGCPInterface_Frequency_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GcpMGCPInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type GcpMGCPInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *GcpMGCPInterface_Expecter) IsCompatibleEntityType(entity interface{}) *GcpMGCPInterface_IsCompatibleEntityType_Call {
	return &GcpMGCPInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *GcpMGCPInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *GcpMGCPInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_IsCompatibleEntityType_Call) Return(b bool) *GcpMGCPInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GcpMGCPInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *GcpMGCPInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GcpMGCPInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type GcpMGCPInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *GcpMGCPInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call {
	return &GcpMGCPInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *GcpMGCPInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// PowerLimitationFactor provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) PowerLimitationFactor() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PowerLimitationFactor")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_PowerLimitationFactor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerLimitationFactor'
type GcpMGCPInterface_PowerLimitationFactor_Call struct {
	*mock.Call
}

// PowerLimitationFactor is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) PowerLimitationFactor() *GcpMGCPInterface_PowerLimitationFactor_Call {
	return &GcpMGCPInterface_PowerLimitationFactor_Call{Call: _e.mock.On("PowerLimitationFactor")}
}

func (_c *GcpMGCPInterface_PowerLimitationFactor_Call) Run(run func()) *GcpMGCPInterface_PowerLimitationFactor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_PowerLimitationFactor_Call) Return(f float64, err error) *GcpMGCPInterface_PowerLimitationFactor_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *GcpMGCPInterface_PowerLimitationFactor_Call) RunAndReturn(run func() (float64, error)) *GcpMGCPInterface_PowerLimitationFactor_Call {
	_c.Call.Return(run)
	return _c
}

// PowerTotal provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) PowerTotal() (float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PowerTotal")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_PowerTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerTotal'
type GcpMGCPInterface_PowerTotal_Call struct {
	*mock.Call
}

// PowerTotal is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) PowerTotal() *GcpMGCPInterface_PowerTotal_Call {
	return &GcpMGCPInterface_PowerTotal_Call{Call: _e.mock.On("PowerTotal")}
}

func (_c *GcpMGCPInterface_PowerTotal_Call) Run(run func()) *GcpMGCPInterface_PowerTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_PowerTotal_Call) Return(f float64, err error) *GcpMGCPInterface_PowerTotal_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *GcpMGCPInterface_PowerTotal_Call) RunAndReturn(run func() (float64, error)) *GcpMGCPInterface_PowerTotal_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) RemoteEntitiesScenarios() []api0.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api0.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api0.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.RemoteEntityScenarios)
		}
	}
	return r0
}

// GcpMGCPInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type GcpMGCPInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) RemoteEntitiesScenarios() *GcpMGCPInterface_RemoteEntitiesScenarios_Call {
	return &GcpMGCPInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *GcpMGCPInterface_RemoteEntitiesScenarios_Call) Run(run func()) *GcpMGCPInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api0.RemoteEntityScenarios) *GcpMGCPInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *GcpMGCPInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api0.RemoteEntityScenarios) *GcpMGCPInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// GcpMGCPInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type GcpMGCPInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) RemoveUseCase() *GcpMGCPInterface_RemoveUseCase_Call {
	return &GcpMGCPInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *GcpMGCPInterface_RemoveUseCase_Call) Run(run func()) *GcpMGCPInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_RemoveUseCase_Call) Return() *GcpMGCPInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *GcpMGCPInterface_RemoveUseCase_Call) RunAndReturn(run func()) *GcpMGCPInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) Update(updateValueTypes ...api1.UpdateData) error {
	var tmpRet mock.Arguments
	if len(updateValueTypes) > 0 {
		tmpRet = _mock.Called(updateValueTypes)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...api1.UpdateData) error); ok {
		r0 = returnFunc(updateValueTypes...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GcpMGCPInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GcpMGCPInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - updateValueTypes ...api1.UpdateData
func (_e *GcpMGCPInterface_Expecter) Update(updateValueTypes ...interface{}) *GcpMGCPInterface_Update_Call {
	return &GcpMGCPInterface_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{}, updateValueTypes...)...)}
}

func (_c *GcpMGCPInterface_Update_Call) Run(run func(updateValueTypes ...api1.UpdateData)) *GcpMGCPInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api1.UpdateData
		var variadicArgs []api1.UpdateData
		if len(args) > 0 {
			variadicArgs = args[0].([]api1.UpdateData)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_Update_Call) Return(err error) *GcpMGCPInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GcpMGCPInterface_Update_Call) RunAndReturn(run func(updateValueTypes ...api1.UpdateData) error) *GcpMGCPInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseA provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataCurrentPhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseA")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataCurrentPhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseA'
type GcpMGCPInterface_UpdateDataCurrentPhaseA_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataCurrentPhaseA(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call {
	return &GcpMGCPInterface_UpdateDataCurrentPhaseA_Call{Call: _e.mock.On("UpdateDataCurrentPhaseA", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseB provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataCurrentPhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseB")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataCurrentPhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseB'
type GcpMGCPInterface_UpdateDataCurrentPhaseB_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataCurrentPhaseB(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call {
	return &GcpMGCPInterface_UpdateDataCurrentPhaseB_Call{Call: _e.mock.On("UpdateDataCurrentPhaseB", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseC provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataCurrentPhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseC")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataCurrentPhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseC'
type GcpMGCPInterface_UpdateDataCurrentPhaseC_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataCurrentPhaseC(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call {
	return &GcpMGCPInterface_UpdateDataCurrentPhaseC_Call{Call: _e.mock.On("UpdateDataCurrentPhaseC", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyConsumed provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataEnergyConsumed(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyConsumed")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataEnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyConsumed'
type GcpMGCPInterface_UpdateDataEnergyConsumed_Call struct {
	*mock.Call
}

// UpdateDataEnergyConsumed is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationPeriodStart *time.Time
//   - evaluationPeriodEnd *time.Time
func (_e *GcpMGCPInterface_Expecter) UpdateDataEnergyConsumed(value interface{}, timestamp interface{}, valueState interface{}, evaluationPeriodStart interface{}, evaluationPeriodEnd interface{}) *GcpMGCPInterface_UpdateDataEnergyConsumed_Call {
	return &GcpMGCPInterface_UpdateDataEnergyConsumed_Call{Call: _e.mock.On("UpdateDataEnergyConsumed", value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)}
}

func (_c *GcpMGCPInterface_UpdateDataEnergyConsumed_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time)) *GcpMGCPInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataEnergyConsumed_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataEnergyConsumed_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time) api1.UpdateData) *GcpMGCPInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyFeedIn provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataEnergyFeedIn(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyFeedIn")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataEnergyFeedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyFeedIn'
type GcpMGCPInterface_UpdateDataEnergyFeedIn_Call struct {
	*mock.Call
}

// UpdateDataEnergyFeedIn is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationPeriodStart *time.Time
//   - evaluationPeriodEnd *time.Time
func (_e *GcpMGCPInterface_Expecter) UpdateDataEnergyFeedIn(value interface{}, timestamp interface{}, valueState interface{}, evaluationPeriodStart interface{}, evaluationPeriodEnd interface{}) *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call {
	return &GcpMGCPInterface_UpdateDataEnergyFeedIn_Call{Call: _e.mock.On("UpdateDataEnergyFeedIn", value, timestamp, valueState, evaluationPeriodStart, evaluationPeriodEnd)}
}

func (_c *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time)) *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationPeriodStart *time.Time, evaluationPeriodEnd *time.Time) api1.UpdateData) *GcpMGCPInterface_UpdateDataEnergyFeedIn_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataFrequency provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataFrequency(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataFrequency")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataFrequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataFrequency'
type GcpMGCPInterface_UpdateDataFrequency_Call struct {
	*mock.Call
}

// UpdateDataFrequency is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataFrequency(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataFrequency_Call {
	return &GcpMGCPInterface_UpdateDataFrequency_Call{Call: _e.mock.On("UpdateDataFrequency", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataFrequency_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataFrequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataFrequency_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataFrequency_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataFrequency_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataFrequency_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerLimitationFactor provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataPowerLimitationFactor(value float64) api1.UpdateData {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerLimitationFactor")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64) api1.UpdateData); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerLimitationFactor'
type GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call struct {
	*mock.Call
}

// UpdateDataPowerLimitationFactor is a helper method to define mock.On call
//   - value float64
func (_e *GcpMGCPInterface_Expecter) UpdateDataPowerLimitationFactor(value interface{}) *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call {
	return &GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call{Call: _e.mock.On("UpdateDataPowerLimitationFactor", value)}
}

func (_c *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call) Run(run func(value float64)) *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call) RunAndReturn(run func(value float64) api1.UpdateData) *GcpMGCPInterface_UpdateDataPowerLimitationFactor_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerTotal provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataPowerTotal(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerTotal")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataPowerTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerTotal'
type GcpMGCPInterface_UpdateDataPowerTotal_Call struct {
	*mock.Call
}

// UpdateDataPowerTotal is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataPowerTotal(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataPowerTotal_Call {
	return &GcpMGCPInterface_UpdateDataPowerTotal_Call{Call: _e.mock.On("UpdateDataPowerTotal", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataPowerTotal_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataPowerTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataPowerTotal_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataPowerTotal_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseA provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseA")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseA'
type GcpMGCPInterface_UpdateDataVoltagePhaseA_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseA(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseA_Call{Call: _e.mock.On("UpdateDataVoltagePhaseA", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseAToB provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseAToB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseAToB")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseAToB'
type GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseAToB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseAToB(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseAToB", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseB provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseB")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseB'
type GcpMGCPInterface_UpdateDataVoltagePhaseB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseB(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseB", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseBToC provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseBToC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseBToC")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseBToC'
type GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseBToC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseBToC(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseBToC", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseC provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseC")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseC'
type GcpMGCPInterface_UpdateDataVoltagePhaseC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseC(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseC", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseCToA provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateDataVoltagePhaseCToA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData {
	ret := _mock.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseCToA")
	}

	var r0 api1.UpdateData
	if returnFunc, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api1.UpdateData); ok {
		r0 = returnFunc(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.UpdateData)
		}
	}
	return r0
}

// GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseCToA'
type GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseCToA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *GcpMGCPInterface_Expecter) UpdateDataVoltagePhaseCToA(value interface{}, timestamp interface{}, valueState interface{}) *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call {
	return &GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call{Call: _e.mock.On("UpdateDataVoltagePhaseCToA", value, timestamp, valueState)}
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *model.MeasurementValueStateType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementValueStateType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call) Return(updateData api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Return(updateData)
	return _c
}

func (_c *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call) RunAndReturn(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api1.UpdateData) *GcpMGCPInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// GcpMGCPInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type GcpMGCPInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *GcpMGCPInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *GcpMGCPInterface_UpdateUseCaseAvailability_Call {
	return &GcpMGCPInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *GcpMGCPInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *GcpMGCPInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GcpMGCPInterface_UpdateUseCaseAvailability_Call) Return() *GcpMGCPInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *GcpMGCPInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *GcpMGCPInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}

// VoltagePerPhase provides a mock function for the type GcpMGCPInterface
func (_mock *GcpMGCPInterface) VoltagePerPhase() ([]float64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VoltagePerPhase")
	}

	var r0 []float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]float64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GcpMGCPInterface_VoltagePerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoltagePerPhase'
type GcpMGCPInterface_VoltagePerPhase_Call struct {
	*mock.Call
}

// VoltagePerPhase is a helper method to define mock.On call
func (_e *GcpMGCPInterface_Expecter) VoltagePerPhase() *GcpMGCPInterface_VoltagePerPhase_Call {
	return &GcpMGCPInterface_VoltagePerPhase_Call{Call: _e.mock.On("VoltagePerPhase")}
}

func (_c *GcpMGCPInterface_VoltagePerPhase_Call) Run(run func()) *GcpMGCPInterface_VoltagePerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GcpMGCPInterface_VoltagePerPhase_Call) Return(float64s []float64, err error) *GcpMGCPInterface_VoltagePerPhase_Call {
	_c.Call.Return(float64s, err)
	return _c
}

func (_c *GcpMGCPInterface_VoltagePerPhase_Call) RunAndReturn(run func() ([]float64, error)) *GcpMGCPInterface_VoltagePerPhase_Call {
	_c.Call.Return(run)
	return _c
}
