// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIdentificationServerInterface creates a new instance of IdentificationServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentificationServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentificationServerInterface {
	mock := &IdentificationServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentificationServerInterface is an autogenerated mock type for the IdentificationServerInterface type
type IdentificationServerInterface struct {
	mock.Mock
}

type IdentificationServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentificationServerInterface) EXPECT() *IdentificationServerInterface_Expecter {
	return &IdentificationServerInterface_Expecter{mock: &_m.Mock}
}
