// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/eebus-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMeasurementServerInterface creates a new instance of MeasurementServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeasurementServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeasurementServerInterface {
	mock := &MeasurementServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MeasurementServerInterface is an autogenerated mock type for the MeasurementServerInterface type
type MeasurementServerInterface struct {
	mock.Mock
}

type MeasurementServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MeasurementServerInterface) EXPECT() *MeasurementServerInterface_Expecter {
	return &MeasurementServerInterface_Expecter{mock: &_m.Mock}
}

// AddDescription provides a mock function for the type MeasurementServerInterface
func (_mock *MeasurementServerInterface) AddDescription(description model.MeasurementDescriptionDataType) *model.MeasurementIdType {
	ret := _mock.Called(description)

	if len(ret) == 0 {
		panic("no return value specified for AddDescription")
	}

	var r0 *model.MeasurementIdType
	if returnFunc, ok := ret.Get(0).(func(model.MeasurementDescriptionDataType) *model.MeasurementIdType); ok {
		r0 = returnFunc(description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MeasurementIdType)
		}
	}
	return r0
}

// MeasurementServerInterface_AddDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDescription'
type MeasurementServerInterface_AddDescription_Call struct {
	*mock.Call
}

// AddDescription is a helper method to define mock.On call
//   - description model.MeasurementDescriptionDataType
func (_e *MeasurementServerInterface_Expecter) AddDescription(description interface{}) *MeasurementServerInterface_AddDescription_Call {
	return &MeasurementServerInterface_AddDescription_Call{Call: _e.mock.On("AddDescription", description)}
}

func (_c *MeasurementServerInterface_AddDescription_Call) Run(run func(description model.MeasurementDescriptionDataType)) *MeasurementServerInterface_AddDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.MeasurementDescriptionDataType
		if args[0] != nil {
			arg0 = args[0].(model.MeasurementDescriptionDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MeasurementServerInterface_AddDescription_Call) Return(measurementIdType *model.MeasurementIdType) *MeasurementServerInterface_AddDescription_Call {
	_c.Call.Return(measurementIdType)
	return _c
}

func (_c *MeasurementServerInterface_AddDescription_Call) RunAndReturn(run func(description model.MeasurementDescriptionDataType) *model.MeasurementIdType) *MeasurementServerInterface_AddDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataForFilters provides a mock function for the type MeasurementServerInterface
func (_mock *MeasurementServerInterface) UpdateDataForFilters(data []api.MeasurementDataForFilter, deleteSelector *model.MeasurementListDataSelectorsType, deleteElements *model.MeasurementDataElementsType) error {
	ret := _mock.Called(data, deleteSelector, deleteElements)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataForFilters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]api.MeasurementDataForFilter, *model.MeasurementListDataSelectorsType, *model.MeasurementDataElementsType) error); ok {
		r0 = returnFunc(data, deleteSelector, deleteElements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MeasurementServerInterface_UpdateDataForFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataForFilters'
type MeasurementServerInterface_UpdateDataForFilters_Call struct {
	*mock.Call
}

// UpdateDataForFilters is a helper method to define mock.On call
//   - data []api.MeasurementDataForFilter
//   - deleteSelector *model.MeasurementListDataSelectorsType
//   - deleteElements *model.MeasurementDataElementsType
func (_e *MeasurementServerInterface_Expecter) UpdateDataForFilters(data interface{}, deleteSelector interface{}, deleteElements interface{}) *MeasurementServerInterface_UpdateDataForFilters_Call {
	return &MeasurementServerInterface_UpdateDataForFilters_Call{Call: _e.mock.On("UpdateDataForFilters", data, deleteSelector, deleteElements)}
}

func (_c *MeasurementServerInterface_UpdateDataForFilters_Call) Run(run func(data []api.MeasurementDataForFilter, deleteSelector *model.MeasurementListDataSelectorsType, deleteElements *model.MeasurementDataElementsType)) *MeasurementServerInterface_UpdateDataForFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.MeasurementDataForFilter
		if args[0] != nil {
			arg0 = args[0].([]api.MeasurementDataForFilter)
		}
		var arg1 *model.MeasurementListDataSelectorsType
		if args[1] != nil {
			arg1 = args[1].(*model.MeasurementListDataSelectorsType)
		}
		var arg2 *model.MeasurementDataElementsType
		if args[2] != nil {
			arg2 = args[2].(*model.MeasurementDataElementsType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MeasurementServerInterface_UpdateDataForFilters_Call) Return(err error) *MeasurementServerInterface_UpdateDataForFilters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MeasurementServerInterface_UpdateDataForFilters_Call) RunAndReturn(run func(data []api.MeasurementDataForFilter, deleteSelector *model.MeasurementListDataSelectorsType, deleteElements *model.MeasurementDataElementsType) error) *MeasurementServerInterface_UpdateDataForFilters_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataForIds provides a mock function for the type MeasurementServerInterface
func (_mock *MeasurementServerInterface) UpdateDataForIds(data []api.MeasurementDataForID) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataForIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]api.MeasurementDataForID) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MeasurementServerInterface_UpdateDataForIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataForIds'
type MeasurementServerInterface_UpdateDataForIds_Call struct {
	*mock.Call
}

// UpdateDataForIds is a helper method to define mock.On call
//   - data []api.MeasurementDataForID
func (_e *MeasurementServerInterface_Expecter) UpdateDataForIds(data interface{}) *MeasurementServerInterface_UpdateDataForIds_Call {
	return &MeasurementServerInterface_UpdateDataForIds_Call{Call: _e.mock.On("UpdateDataForIds", data)}
}

func (_c *MeasurementServerInterface_UpdateDataForIds_Call) Run(run func(data []api.MeasurementDataForID)) *MeasurementServerInterface_UpdateDataForIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.MeasurementDataForID
		if args[0] != nil {
			arg0 = args[0].([]api.MeasurementDataForID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MeasurementServerInterface_UpdateDataForIds_Call) Return(err error) *MeasurementServerInterface_UpdateDataForIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MeasurementServerInterface_UpdateDataForIds_Call) RunAndReturn(run func(data []api.MeasurementDataForID) error) *MeasurementServerInterface_UpdateDataForIds_Call {
	_c.Call.Return(run)
	return _c
}
