// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/eebus-go/api"
	api0 "github.com/enbility/ship-go/api"
	"github.com/enbility/ship-go/logging"
	api1 "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceInterface creates a new instance of ServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterface {
	mock := &ServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

type ServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterface) EXPECT() *ServiceInterface_Expecter {
	return &ServiceInterface_Expecter{mock: &_m.Mock}
}

// AddUseCase provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) AddUseCase(useCase api.UseCaseInterface) error {
	ret := _mock.Called(useCase)

	if len(ret) == 0 {
		panic("no return value specified for AddUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api.UseCaseInterface) error); ok {
		r0 = returnFunc(useCase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type ServiceInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
//   - useCase api.UseCaseInterface
func (_e *ServiceInterface_Expecter) AddUseCase(useCase interface{}) *ServiceInterface_AddUseCase_Call {
	return &ServiceInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase", useCase)}
}

func (_c *ServiceInterface_AddUseCase_Call) Run(run func(useCase api.UseCaseInterface)) *ServiceInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.UseCaseInterface
		if args[0] != nil {
			arg0 = args[0].(api.UseCaseInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_AddUseCase_Call) Return(err error) *ServiceInterface_AddUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceInterface_AddUseCase_Call) RunAndReturn(run func(useCase api.UseCaseInterface) error) *ServiceInterface_AddUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPairing provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) CancelPairing(identity api0.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// ServiceInterface_CancelPairing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPairing'
type ServiceInterface_CancelPairing_Call struct {
	*mock.Call
}

// CancelPairing is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
func (_e *ServiceInterface_Expecter) CancelPairing(identity interface{}) *ServiceInterface_CancelPairing_Call {
	return &ServiceInterface_CancelPairing_Call{Call: _e.mock.On("CancelPairing", identity)}
}

func (_c *ServiceInterface_CancelPairing_Call) Run(run func(identity api0.ServiceIdentity)) *ServiceInterface_CancelPairing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_CancelPairing_Call) Return() *ServiceInterface_CancelPairing_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_CancelPairing_Call) RunAndReturn(run func(identity api0.ServiceIdentity)) *ServiceInterface_CancelPairing_Call {
	_c.Run(run)
	return _c
}

// Configuration provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) Configuration() *api.Configuration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Configuration")
	}

	var r0 *api.Configuration
	if returnFunc, ok := ret.Get(0).(func() *api.Configuration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Configuration)
		}
	}
	return r0
}

// ServiceInterface_Configuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configuration'
type ServiceInterface_Configuration_Call struct {
	*mock.Call
}

// Configuration is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) Configuration() *ServiceInterface_Configuration_Call {
	return &ServiceInterface_Configuration_Call{Call: _e.mock.On("Configuration")}
}

func (_c *ServiceInterface_Configuration_Call) Run(run func()) *ServiceInterface_Configuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_Configuration_Call) Return(configuration *api.Configuration) *ServiceInterface_Configuration_Call {
	_c.Call.Return(configuration)
	return _c
}

func (_c *ServiceInterface_Configuration_Call) RunAndReturn(run func() *api.Configuration) *ServiceInterface_Configuration_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectService provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) DisconnectService(identity api0.ServiceIdentity, reason string) {
	_mock.Called(identity, reason)
	return
}

// ServiceInterface_DisconnectService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectService'
type ServiceInterface_DisconnectService_Call struct {
	*mock.Call
}

// DisconnectService is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
//   - reason string
func (_e *ServiceInterface_Expecter) DisconnectService(identity interface{}, reason interface{}) *ServiceInterface_DisconnectService_Call {
	return &ServiceInterface_DisconnectService_Call{Call: _e.mock.On("DisconnectService", identity, reason)}
}

func (_c *ServiceInterface_DisconnectService_Call) Run(run func(identity api0.ServiceIdentity, reason string)) *ServiceInterface_DisconnectService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceInterface_DisconnectService_Call) Return() *ServiceInterface_DisconnectService_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_DisconnectService_Call) RunAndReturn(run func(identity api0.ServiceIdentity, reason string)) *ServiceInterface_DisconnectService_Call {
	_c.Run(run)
	return _c
}

// GetActiveAnnouncements provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) GetActiveAnnouncements() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveAnnouncements")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// ServiceInterface_GetActiveAnnouncements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveAnnouncements'
type ServiceInterface_GetActiveAnnouncements_Call struct {
	*mock.Call
}

// GetActiveAnnouncements is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) GetActiveAnnouncements() *ServiceInterface_GetActiveAnnouncements_Call {
	return &ServiceInterface_GetActiveAnnouncements_Call{Call: _e.mock.On("GetActiveAnnouncements")}
}

func (_c *ServiceInterface_GetActiveAnnouncements_Call) Run(run func()) *ServiceInterface_GetActiveAnnouncements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_GetActiveAnnouncements_Call) Return(strings []string) *ServiceInterface_GetActiveAnnouncements_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *ServiceInterface_GetActiveAnnouncements_Call) RunAndReturn(run func() []string) *ServiceInterface_GetActiveAnnouncements_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalCertificateFingerprint provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) GetLocalCertificateFingerprint() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalCertificateFingerprint")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceInterface_GetLocalCertificateFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalCertificateFingerprint'
type ServiceInterface_GetLocalCertificateFingerprint_Call struct {
	*mock.Call
}

// GetLocalCertificateFingerprint is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) GetLocalCertificateFingerprint() *ServiceInterface_GetLocalCertificateFingerprint_Call {
	return &ServiceInterface_GetLocalCertificateFingerprint_Call{Call: _e.mock.On("GetLocalCertificateFingerprint")}
}

func (_c *ServiceInterface_GetLocalCertificateFingerprint_Call) Run(run func()) *ServiceInterface_GetLocalCertificateFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_GetLocalCertificateFingerprint_Call) Return(s string, err error) *ServiceInterface_GetLocalCertificateFingerprint_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ServiceInterface_GetLocalCertificateFingerprint_Call) RunAndReturn(run func() (string, error)) *ServiceInterface_GetLocalCertificateFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrustedAddCuDevice provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) GetTrustedAddCuDevice() *api0.ServiceDetails {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTrustedAddCuDevice")
	}

	var r0 *api0.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func() *api0.ServiceDetails); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api0.ServiceDetails)
		}
	}
	return r0
}

// ServiceInterface_GetTrustedAddCuDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrustedAddCuDevice'
type ServiceInterface_GetTrustedAddCuDevice_Call struct {
	*mock.Call
}

// GetTrustedAddCuDevice is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) GetTrustedAddCuDevice() *ServiceInterface_GetTrustedAddCuDevice_Call {
	return &ServiceInterface_GetTrustedAddCuDevice_Call{Call: _e.mock.On("GetTrustedAddCuDevice")}
}

func (_c *ServiceInterface_GetTrustedAddCuDevice_Call) Run(run func()) *ServiceInterface_GetTrustedAddCuDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_GetTrustedAddCuDevice_Call) Return(serviceDetails *api0.ServiceDetails) *ServiceInterface_GetTrustedAddCuDevice_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *ServiceInterface_GetTrustedAddCuDevice_Call) RunAndReturn(run func() *api0.ServiceDetails) *ServiceInterface_GetTrustedAddCuDevice_Call {
	_c.Call.Return(run)
	return _c
}

// IsAnnouncingTo provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) IsAnnouncingTo(shipID string) bool {
	ret := _mock.Called(shipID)

	if len(ret) == 0 {
		panic("no return value specified for IsAnnouncingTo")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(shipID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ServiceInterface_IsAnnouncingTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAnnouncingTo'
type ServiceInterface_IsAnnouncingTo_Call struct {
	*mock.Call
}

// IsAnnouncingTo is a helper method to define mock.On call
//   - shipID string
func (_e *ServiceInterface_Expecter) IsAnnouncingTo(shipID interface{}) *ServiceInterface_IsAnnouncingTo_Call {
	return &ServiceInterface_IsAnnouncingTo_Call{Call: _e.mock.On("IsAnnouncingTo", shipID)}
}

func (_c *ServiceInterface_IsAnnouncingTo_Call) Run(run func(shipID string)) *ServiceInterface_IsAnnouncingTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_IsAnnouncingTo_Call) Return(b bool) *ServiceInterface_IsAnnouncingTo_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ServiceInterface_IsAnnouncingTo_Call) RunAndReturn(run func(shipID string) bool) *ServiceInterface_IsAnnouncingTo_Call {
	_c.Call.Return(run)
	return _c
}

// IsAutoAcceptEnabled provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) IsAutoAcceptEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAutoAcceptEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ServiceInterface_IsAutoAcceptEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAutoAcceptEnabled'
type ServiceInterface_IsAutoAcceptEnabled_Call struct {
	*mock.Call
}

// IsAutoAcceptEnabled is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) IsAutoAcceptEnabled() *ServiceInterface_IsAutoAcceptEnabled_Call {
	return &ServiceInterface_IsAutoAcceptEnabled_Call{Call: _e.mock.On("IsAutoAcceptEnabled")}
}

func (_c *ServiceInterface_IsAutoAcceptEnabled_Call) Run(run func()) *ServiceInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_IsAutoAcceptEnabled_Call) Return(b bool) *ServiceInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ServiceInterface_IsAutoAcceptEnabled_Call) RunAndReturn(run func() bool) *ServiceInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ServiceInterface_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type ServiceInterface_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) IsRunning() *ServiceInterface_IsRunning_Call {
	return &ServiceInterface_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *ServiceInterface_IsRunning_Call) Run(run func()) *ServiceInterface_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_IsRunning_Call) Return(b bool) *ServiceInterface_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ServiceInterface_IsRunning_Call) RunAndReturn(run func() bool) *ServiceInterface_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// LocalDevice provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) LocalDevice() api1.DeviceLocalInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalDevice")
	}

	var r0 api1.DeviceLocalInterface
	if returnFunc, ok := ret.Get(0).(func() api1.DeviceLocalInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api1.DeviceLocalInterface)
		}
	}
	return r0
}

// ServiceInterface_LocalDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalDevice'
type ServiceInterface_LocalDevice_Call struct {
	*mock.Call
}

// LocalDevice is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) LocalDevice() *ServiceInterface_LocalDevice_Call {
	return &ServiceInterface_LocalDevice_Call{Call: _e.mock.On("LocalDevice")}
}

func (_c *ServiceInterface_LocalDevice_Call) Run(run func()) *ServiceInterface_LocalDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_LocalDevice_Call) Return(deviceLocalInterface api1.DeviceLocalInterface) *ServiceInterface_LocalDevice_Call {
	_c.Call.Return(deviceLocalInterface)
	return _c
}

func (_c *ServiceInterface_LocalDevice_Call) RunAndReturn(run func() api1.DeviceLocalInterface) *ServiceInterface_LocalDevice_Call {
	_c.Call.Return(run)
	return _c
}

// LocalService provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) LocalService() *api0.ServiceDetails {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalService")
	}

	var r0 *api0.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func() *api0.ServiceDetails); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api0.ServiceDetails)
		}
	}
	return r0
}

// ServiceInterface_LocalService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalService'
type ServiceInterface_LocalService_Call struct {
	*mock.Call
}

// LocalService is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) LocalService() *ServiceInterface_LocalService_Call {
	return &ServiceInterface_LocalService_Call{Call: _e.mock.On("LocalService")}
}

func (_c *ServiceInterface_LocalService_Call) Run(run func()) *ServiceInterface_LocalService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_LocalService_Call) Return(serviceDetails *api0.ServiceDetails) *ServiceInterface_LocalService_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *ServiceInterface_LocalService_Call) RunAndReturn(run func() *api0.ServiceDetails) *ServiceInterface_LocalService_Call {
	_c.Call.Return(run)
	return _c
}

// PairingDetailFor provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) PairingDetailFor(identity api0.ServiceIdentity) *api0.ConnectionStateDetail {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for PairingDetailFor")
	}

	var r0 *api0.ConnectionStateDetail
	if returnFunc, ok := ret.Get(0).(func(api0.ServiceIdentity) *api0.ConnectionStateDetail); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api0.ConnectionStateDetail)
		}
	}
	return r0
}

// ServiceInterface_PairingDetailFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingDetailFor'
type ServiceInterface_PairingDetailFor_Call struct {
	*mock.Call
}

// PairingDetailFor is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
func (_e *ServiceInterface_Expecter) PairingDetailFor(identity interface{}) *ServiceInterface_PairingDetailFor_Call {
	return &ServiceInterface_PairingDetailFor_Call{Call: _e.mock.On("PairingDetailFor", identity)}
}

func (_c *ServiceInterface_PairingDetailFor_Call) Run(run func(identity api0.ServiceIdentity)) *ServiceInterface_PairingDetailFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_PairingDetailFor_Call) Return(connectionStateDetail *api0.ConnectionStateDetail) *ServiceInterface_PairingDetailFor_Call {
	_c.Call.Return(connectionStateDetail)
	return _c
}

func (_c *ServiceInterface_PairingDetailFor_Call) RunAndReturn(run func(identity api0.ServiceIdentity) *api0.ConnectionStateDetail) *ServiceInterface_PairingDetailFor_Call {
	_c.Call.Return(run)
	return _c
}

// QRCodeText provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) QRCodeText() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for QRCodeText")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceInterface_QRCodeText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QRCodeText'
type ServiceInterface_QRCodeText_Call struct {
	*mock.Call
}

// QRCodeText is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) QRCodeText() *ServiceInterface_QRCodeText_Call {
	return &ServiceInterface_QRCodeText_Call{Call: _e.mock.On("QRCodeText")}
}

func (_c *ServiceInterface_QRCodeText_Call) Run(run func()) *ServiceInterface_QRCodeText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_QRCodeText_Call) Return(s string, err error) *ServiceInterface_QRCodeText_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ServiceInterface_QRCodeText_Call) RunAndReturn(run func() (string, error)) *ServiceInterface_QRCodeText_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRemoteService provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) RegisterRemoteService(identity api0.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// ServiceInterface_RegisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRemoteService'
type ServiceInterface_RegisterRemoteService_Call struct {
	*mock.Call
}

// RegisterRemoteService is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
func (_e *ServiceInterface_Expecter) RegisterRemoteService(identity interface{}) *ServiceInterface_RegisterRemoteService_Call {
	return &ServiceInterface_RegisterRemoteService_Call{Call: _e.mock.On("RegisterRemoteService", identity)}
}

func (_c *ServiceInterface_RegisterRemoteService_Call) Run(run func(identity api0.ServiceIdentity)) *ServiceInterface_RegisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_RegisterRemoteService_Call) Return() *ServiceInterface_RegisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_RegisterRemoteService_Call) RunAndReturn(run func(identity api0.ServiceIdentity)) *ServiceInterface_RegisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// RemoteServiceFor provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) RemoteServiceFor(identity api0.ServiceIdentity) *api0.ServiceDetails {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for RemoteServiceFor")
	}

	var r0 *api0.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(api0.ServiceIdentity) *api0.ServiceDetails); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api0.ServiceDetails)
		}
	}
	return r0
}

// ServiceInterface_RemoteServiceFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteServiceFor'
type ServiceInterface_RemoteServiceFor_Call struct {
	*mock.Call
}

// RemoteServiceFor is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
func (_e *ServiceInterface_Expecter) RemoteServiceFor(identity interface{}) *ServiceInterface_RemoteServiceFor_Call {
	return &ServiceInterface_RemoteServiceFor_Call{Call: _e.mock.On("RemoteServiceFor", identity)}
}

func (_c *ServiceInterface_RemoteServiceFor_Call) Run(run func(identity api0.ServiceIdentity)) *ServiceInterface_RemoteServiceFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_RemoteServiceFor_Call) Return(serviceDetails *api0.ServiceDetails) *ServiceInterface_RemoteServiceFor_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *ServiceInterface_RemoteServiceFor_Call) RunAndReturn(run func(identity api0.ServiceIdentity) *api0.ServiceDetails) *ServiceInterface_RemoteServiceFor_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoAccept provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) SetAutoAccept(value bool) {
	_mock.Called(value)
	return
}

// ServiceInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type ServiceInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - value bool
func (_e *ServiceInterface_Expecter) SetAutoAccept(value interface{}) *ServiceInterface_SetAutoAccept_Call {
	return &ServiceInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", value)}
}

func (_c *ServiceInterface_SetAutoAccept_Call) Run(run func(value bool)) *ServiceInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_SetAutoAccept_Call) Return() *ServiceInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_SetAutoAccept_Call) RunAndReturn(run func(value bool)) *ServiceInterface_SetAutoAccept_Call {
	_c.Run(run)
	return _c
}

// SetLogging provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) SetLogging(logger logging.LoggingInterface) {
	_mock.Called(logger)
	return
}

// ServiceInterface_SetLogging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogging'
type ServiceInterface_SetLogging_Call struct {
	*mock.Call
}

// SetLogging is a helper method to define mock.On call
//   - logger logging.LoggingInterface
func (_e *ServiceInterface_Expecter) SetLogging(logger interface{}) *ServiceInterface_SetLogging_Call {
	return &ServiceInterface_SetLogging_Call{Call: _e.mock.On("SetLogging", logger)}
}

func (_c *ServiceInterface_SetLogging_Call) Run(run func(logger logging.LoggingInterface)) *ServiceInterface_SetLogging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logging.LoggingInterface
		if args[0] != nil {
			arg0 = args[0].(logging.LoggingInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_SetLogging_Call) Return() *ServiceInterface_SetLogging_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_SetLogging_Call) RunAndReturn(run func(logger logging.LoggingInterface)) *ServiceInterface_SetLogging_Call {
	_c.Run(run)
	return _c
}

// Setup provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) Setup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type ServiceInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) Setup() *ServiceInterface_Setup_Call {
	return &ServiceInterface_Setup_Call{Call: _e.mock.On("Setup")}
}

func (_c *ServiceInterface_Setup_Call) Run(run func()) *ServiceInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_Setup_Call) Return(err error) *ServiceInterface_Setup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceInterface_Setup_Call) RunAndReturn(run func() error) *ServiceInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) Shutdown() {
	_mock.Called()
	return
}

// ServiceInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ServiceInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) Shutdown() *ServiceInterface_Shutdown_Call {
	return &ServiceInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *ServiceInterface_Shutdown_Call) Run(run func()) *ServiceInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_Shutdown_Call) Return() *ServiceInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_Shutdown_Call) RunAndReturn(run func()) *ServiceInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ServiceInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *ServiceInterface_Expecter) Start() *ServiceInterface_Start_Call {
	return &ServiceInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *ServiceInterface_Start_Call) Run(run func()) *ServiceInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceInterface_Start_Call) Return(err error) *ServiceInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceInterface_Start_Call) RunAndReturn(run func() error) *ServiceInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartAnnouncementTo provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) StartAnnouncementTo(target api0.PairingTarget) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for StartAnnouncementTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api0.PairingTarget) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceInterface_StartAnnouncementTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAnnouncementTo'
type ServiceInterface_StartAnnouncementTo_Call struct {
	*mock.Call
}

// StartAnnouncementTo is a helper method to define mock.On call
//   - target api0.PairingTarget
func (_e *ServiceInterface_Expecter) StartAnnouncementTo(target interface{}) *ServiceInterface_StartAnnouncementTo_Call {
	return &ServiceInterface_StartAnnouncementTo_Call{Call: _e.mock.On("StartAnnouncementTo", target)}
}

func (_c *ServiceInterface_StartAnnouncementTo_Call) Run(run func(target api0.PairingTarget)) *ServiceInterface_StartAnnouncementTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.PairingTarget
		if args[0] != nil {
			arg0 = args[0].(api0.PairingTarget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_StartAnnouncementTo_Call) Return(err error) *ServiceInterface_StartAnnouncementTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceInterface_StartAnnouncementTo_Call) RunAndReturn(run func(target api0.PairingTarget) error) *ServiceInterface_StartAnnouncementTo_Call {
	_c.Call.Return(run)
	return _c
}

// StopAnnouncementTo provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) StopAnnouncementTo(shipID string) error {
	ret := _mock.Called(shipID)

	if len(ret) == 0 {
		panic("no return value specified for StopAnnouncementTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(shipID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceInterface_StopAnnouncementTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAnnouncementTo'
type ServiceInterface_StopAnnouncementTo_Call struct {
	*mock.Call
}

// StopAnnouncementTo is a helper method to define mock.On call
//   - shipID string
func (_e *ServiceInterface_Expecter) StopAnnouncementTo(shipID interface{}) *ServiceInterface_StopAnnouncementTo_Call {
	return &ServiceInterface_StopAnnouncementTo_Call{Call: _e.mock.On("StopAnnouncementTo", shipID)}
}

func (_c *ServiceInterface_StopAnnouncementTo_Call) Run(run func(shipID string)) *ServiceInterface_StopAnnouncementTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_StopAnnouncementTo_Call) Return(err error) *ServiceInterface_StopAnnouncementTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceInterface_StopAnnouncementTo_Call) RunAndReturn(run func(shipID string) error) *ServiceInterface_StopAnnouncementTo_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterRemoteService provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) UnregisterRemoteService(identity api0.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// ServiceInterface_UnregisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRemoteService'
type ServiceInterface_UnregisterRemoteService_Call struct {
	*mock.Call
}

// UnregisterRemoteService is a helper method to define mock.On call
//   - identity api0.ServiceIdentity
func (_e *ServiceInterface_Expecter) UnregisterRemoteService(identity interface{}) *ServiceInterface_UnregisterRemoteService_Call {
	return &ServiceInterface_UnregisterRemoteService_Call{Call: _e.mock.On("UnregisterRemoteService", identity)}
}

func (_c *ServiceInterface_UnregisterRemoteService_Call) Run(run func(identity api0.ServiceIdentity)) *ServiceInterface_UnregisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api0.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api0.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_UnregisterRemoteService_Call) Return() *ServiceInterface_UnregisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_UnregisterRemoteService_Call) RunAndReturn(run func(identity api0.ServiceIdentity)) *ServiceInterface_UnregisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// UserIsAbleToApproveOrCancelPairingRequests provides a mock function for the type ServiceInterface
func (_mock *ServiceInterface) UserIsAbleToApproveOrCancelPairingRequests(allow bool) {
	_mock.Called(allow)
	return
}

// ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserIsAbleToApproveOrCancelPairingRequests'
type ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call struct {
	*mock.Call
}

// UserIsAbleToApproveOrCancelPairingRequests is a helper method to define mock.On call
//   - allow bool
func (_e *ServiceInterface_Expecter) UserIsAbleToApproveOrCancelPairingRequests(allow interface{}) *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call {
	return &ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call{Call: _e.mock.On("UserIsAbleToApproveOrCancelPairingRequests", allow)}
}

func (_c *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call) Run(run func(allow bool)) *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call) Return() *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call) RunAndReturn(run func(allow bool)) *ServiceInterface_UserIsAbleToApproveOrCancelPairingRequests_Call {
	_c.Run(run)
	return _c
}
