// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSmartEnergyManagementPsCommonInterface creates a new instance of SmartEnergyManagementPsCommonInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSmartEnergyManagementPsCommonInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SmartEnergyManagementPsCommonInterface {
	mock := &SmartEnergyManagementPsCommonInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SmartEnergyManagementPsCommonInterface is an autogenerated mock type for the SmartEnergyManagementPsCommonInterface type
type SmartEnergyManagementPsCommonInterface struct {
	mock.Mock
}

type SmartEnergyManagementPsCommonInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *SmartEnergyManagementPsCommonInterface) EXPECT() *SmartEnergyManagementPsCommonInterface_Expecter {
	return &SmartEnergyManagementPsCommonInterface_Expecter{mock: &_m.Mock}
}

// GetData provides a mock function for the type SmartEnergyManagementPsCommonInterface
func (_mock *SmartEnergyManagementPsCommonInterface) GetData() (*model.SmartEnergyManagementPsDataType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 *model.SmartEnergyManagementPsDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.SmartEnergyManagementPsDataType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.SmartEnergyManagementPsDataType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SmartEnergyManagementPsDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SmartEnergyManagementPsCommonInterface_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type SmartEnergyManagementPsCommonInterface_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *SmartEnergyManagementPsCommonInterface_Expecter) GetData() *SmartEnergyManagementPsCommonInterface_GetData_Call {
	return &SmartEnergyManagementPsCommonInterface_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *SmartEnergyManagementPsCommonInterface_GetData_Call) Run(run func()) *SmartEnergyManagementPsCommonInterface_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SmartEnergyManagementPsCommonInterface_GetData_Call) Return(smartEnergyManagementPsDataType *model.SmartEnergyManagementPsDataType, err error) *SmartEnergyManagementPsCommonInterface_GetData_Call {
	_c.Call.Return(smartEnergyManagementPsDataType, err)
	return _c
}

func (_c *SmartEnergyManagementPsCommonInterface_GetData_Call) RunAndReturn(run func() (*model.SmartEnergyManagementPsDataType, error)) *SmartEnergyManagementPsCommonInterface_GetData_Call {
	_c.Call.Return(run)
	return _c
}
