// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTimeSeriesClientInterface creates a new instance of TimeSeriesClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeSeriesClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeSeriesClientInterface {
	mock := &TimeSeriesClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TimeSeriesClientInterface is an autogenerated mock type for the TimeSeriesClientInterface type
type TimeSeriesClientInterface struct {
	mock.Mock
}

type TimeSeriesClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeSeriesClientInterface) EXPECT() *TimeSeriesClientInterface_Expecter {
	return &TimeSeriesClientInterface_Expecter{mock: &_m.Mock}
}

// RequestConstraints provides a mock function for the type TimeSeriesClientInterface
func (_mock *TimeSeriesClientInterface) RequestConstraints(selector *model.TimeSeriesConstraintsListDataSelectorsType, elements *model.TimeSeriesConstraintsDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestConstraints")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesConstraintsListDataSelectorsType, *model.TimeSeriesConstraintsDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesConstraintsListDataSelectorsType, *model.TimeSeriesConstraintsDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.TimeSeriesConstraintsListDataSelectorsType, *model.TimeSeriesConstraintsDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TimeSeriesClientInterface_RequestConstraints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestConstraints'
type TimeSeriesClientInterface_RequestConstraints_Call struct {
	*mock.Call
}

// RequestConstraints is a helper method to define mock.On call
//   - selector *model.TimeSeriesConstraintsListDataSelectorsType
//   - elements *model.TimeSeriesConstraintsDataElementsType
func (_e *TimeSeriesClientInterface_Expecter) RequestConstraints(selector interface{}, elements interface{}) *TimeSeriesClientInterface_RequestConstraints_Call {
	return &TimeSeriesClientInterface_RequestConstraints_Call{Call: _e.mock.On("RequestConstraints", selector, elements)}
}

func (_c *TimeSeriesClientInterface_RequestConstraints_Call) Run(run func(selector *model.TimeSeriesConstraintsListDataSelectorsType, elements *model.TimeSeriesConstraintsDataElementsType)) *TimeSeriesClientInterface_RequestConstraints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TimeSeriesConstraintsListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.TimeSeriesConstraintsListDataSelectorsType)
		}
		var arg1 *model.TimeSeriesConstraintsDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.TimeSeriesConstraintsDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TimeSeriesClientInterface_RequestConstraints_Call) Return(msgCounterType *model.MsgCounterType, err error) *TimeSeriesClientInterface_RequestConstraints_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *TimeSeriesClientInterface_RequestConstraints_Call) RunAndReturn(run func(selector *model.TimeSeriesConstraintsListDataSelectorsType, elements *model.TimeSeriesConstraintsDataElementsType) (*model.MsgCounterType, error)) *TimeSeriesClientInterface_RequestConstraints_Call {
	_c.Call.Return(run)
	return _c
}

// RequestData provides a mock function for the type TimeSeriesClientInterface
func (_mock *TimeSeriesClientInterface) RequestData(selector *model.TimeSeriesListDataSelectorsType, elements *model.TimeSeriesDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesListDataSelectorsType, *model.TimeSeriesDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesListDataSelectorsType, *model.TimeSeriesDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.TimeSeriesListDataSelectorsType, *model.TimeSeriesDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TimeSeriesClientInterface_RequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestData'
type TimeSeriesClientInterface_RequestData_Call struct {
	*mock.Call
}

// RequestData is a helper method to define mock.On call
//   - selector *model.TimeSeriesListDataSelectorsType
//   - elements *model.TimeSeriesDataElementsType
func (_e *TimeSeriesClientInterface_Expecter) RequestData(selector interface{}, elements interface{}) *TimeSeriesClientInterface_RequestData_Call {
	return &TimeSeriesClientInterface_RequestData_Call{Call: _e.mock.On("RequestData", selector, elements)}
}

func (_c *TimeSeriesClientInterface_RequestData_Call) Run(run func(selector *model.TimeSeriesListDataSelectorsType, elements *model.TimeSeriesDataElementsType)) *TimeSeriesClientInterface_RequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TimeSeriesListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.TimeSeriesListDataSelectorsType)
		}
		var arg1 *model.TimeSeriesDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.TimeSeriesDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TimeSeriesClientInterface_RequestData_Call) Return(msgCounterType *model.MsgCounterType, err error) *TimeSeriesClientInterface_RequestData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *TimeSeriesClientInterface_RequestData_Call) RunAndReturn(run func(selector *model.TimeSeriesListDataSelectorsType, elements *model.TimeSeriesDataElementsType) (*model.MsgCounterType, error)) *TimeSeriesClientInterface_RequestData_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDescriptions provides a mock function for the type TimeSeriesClientInterface
func (_mock *TimeSeriesClientInterface) RequestDescriptions(selector *model.TimeSeriesDescriptionListDataSelectorsType, elements *model.TimeSeriesDescriptionDataElementsType) (*model.MsgCounterType, error) {
	ret := _mock.Called(selector, elements)

	if len(ret) == 0 {
		panic("no return value specified for RequestDescriptions")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesDescriptionListDataSelectorsType, *model.TimeSeriesDescriptionDataElementsType) (*model.MsgCounterType, error)); ok {
		return returnFunc(selector, elements)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.TimeSeriesDescriptionListDataSelectorsType, *model.TimeSeriesDescriptionDataElementsType) *model.MsgCounterType); ok {
		r0 = returnFunc(selector, elements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.TimeSeriesDescriptionListDataSelectorsType, *model.TimeSeriesDescriptionDataElementsType) error); ok {
		r1 = returnFunc(selector, elements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TimeSeriesClientInterface_RequestDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDescriptions'
type TimeSeriesClientInterface_RequestDescriptions_Call struct {
	*mock.Call
}

// RequestDescriptions is a helper method to define mock.On call
//   - selector *model.TimeSeriesDescriptionListDataSelectorsType
//   - elements *model.TimeSeriesDescriptionDataElementsType
func (_e *TimeSeriesClientInterface_Expecter) RequestDescriptions(selector interface{}, elements interface{}) *TimeSeriesClientInterface_RequestDescriptions_Call {
	return &TimeSeriesClientInterface_RequestDescriptions_Call{Call: _e.mock.On("RequestDescriptions", selector, elements)}
}

func (_c *TimeSeriesClientInterface_RequestDescriptions_Call) Run(run func(selector *model.TimeSeriesDescriptionListDataSelectorsType, elements *model.TimeSeriesDescriptionDataElementsType)) *TimeSeriesClientInterface_RequestDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TimeSeriesDescriptionListDataSelectorsType
		if args[0] != nil {
			arg0 = args[0].(*model.TimeSeriesDescriptionListDataSelectorsType)
		}
		var arg1 *model.TimeSeriesDescriptionDataElementsType
		if args[1] != nil {
			arg1 = args[1].(*model.TimeSeriesDescriptionDataElementsType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TimeSeriesClientInterface_RequestDescriptions_Call) Return(msgCounterType *model.MsgCounterType, err error) *TimeSeriesClientInterface_RequestDescriptions_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *TimeSeriesClientInterface_RequestDescriptions_Call) RunAndReturn(run func(selector *model.TimeSeriesDescriptionListDataSelectorsType, elements *model.TimeSeriesDescriptionDataElementsType) (*model.MsgCounterType, error)) *TimeSeriesClientInterface_RequestDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// WriteData provides a mock function for the type TimeSeriesClientInterface
func (_mock *TimeSeriesClientInterface) WriteData(data []model.TimeSeriesDataType) (*model.MsgCounterType, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for WriteData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]model.TimeSeriesDataType) (*model.MsgCounterType, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]model.TimeSeriesDataType) *model.MsgCounterType); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]model.TimeSeriesDataType) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TimeSeriesClientInterface_WriteData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteData'
type TimeSeriesClientInterface_WriteData_Call struct {
	*mock.Call
}

// WriteData is a helper method to define mock.On call
//   - data []model.TimeSeriesDataType
func (_e *TimeSeriesClientInterface_Expecter) WriteData(data interface{}) *TimeSeriesClientInterface_WriteData_Call {
	return &TimeSeriesClientInterface_WriteData_Call{Call: _e.mock.On("WriteData", data)}
}

func (_c *TimeSeriesClientInterface_WriteData_Call) Run(run func(data []model.TimeSeriesDataType)) *TimeSeriesClientInterface_WriteData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []model.TimeSeriesDataType
		if args[0] != nil {
			arg0 = args[0].([]model.TimeSeriesDataType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TimeSeriesClientInterface_WriteData_Call) Return(msgCounterType *model.MsgCounterType, err error) *TimeSeriesClientInterface_WriteData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *TimeSeriesClientInterface_WriteData_Call) RunAndReturn(run func(data []model.TimeSeriesDataType) (*model.MsgCounterType, error)) *TimeSeriesClientInterface_WriteData_Call {
	_c.Call.Return(run)
	return _c
}
